/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as ClubedascolecionadorasSignupRouteImport } from './routes/clubedascolecionadoras/signup'
import { Route as ClubedascolecionadorasLoginRouteImport } from './routes/clubedascolecionadoras/login'
import { Route as ClubedascolecionadorasConfirmarEmailRouteImport } from './routes/clubedascolecionadoras/confirmar-email'
import { Route as ClubedascolecionadorasDashboardRouteImport } from './routes/clubedascolecionadoras/_dashboard'
import { Route as ClubedascolecionadorasDashboardIndexRouteImport } from './routes/clubedascolecionadoras/_dashboard/index'
import { Route as ClubedascolecionadorasDashboardTrocasRouteImport } from './routes/clubedascolecionadoras/_dashboard/trocas'
import { Route as ClubedascolecionadorasDashboardRegistrosRouteImport } from './routes/clubedascolecionadoras/_dashboard/registros'
import { Route as ClubedascolecionadorasDashboardQuizRouteImport } from './routes/clubedascolecionadoras/_dashboard/quiz'
import { Route as ClubedascolecionadorasDashboardMuralRouteImport } from './routes/clubedascolecionadoras/_dashboard/mural'
import { Route as ClubedascolecionadorasDashboardLojaRouteImport } from './routes/clubedascolecionadoras/_dashboard/loja'
import { Route as ClubedascolecionadorasDashboardDoarRouteImport } from './routes/clubedascolecionadoras/_dashboard/doar'
import { Route as ClubedascolecionadorasDashboardConfigRouteImport } from './routes/clubedascolecionadoras/_dashboard/config'
import { Route as ClubedascolecionadorasDashboardCodigosRouteImport } from './routes/clubedascolecionadoras/_dashboard/codigos'
import { Route as ClubedascolecionadorasDashboardAlbumRouteImport } from './routes/clubedascolecionadoras/_dashboard/album'
import { Route as ClubedascolecionadorasAlbumUIdRouteImport } from './routes/clubedascolecionadoras/album.u.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubedascolecionadorasSignupRoute =
  ClubedascolecionadorasSignupRouteImport.update({
    id: '/clubedascolecionadoras/signup',
    path: '/clubedascolecionadoras/signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubedascolecionadorasLoginRoute =
  ClubedascolecionadorasLoginRouteImport.update({
    id: '/clubedascolecionadoras/login',
    path: '/clubedascolecionadoras/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubedascolecionadorasConfirmarEmailRoute =
  ClubedascolecionadorasConfirmarEmailRouteImport.update({
    id: '/clubedascolecionadoras/confirmar-email',
    path: '/clubedascolecionadoras/confirmar-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubedascolecionadorasDashboardRoute =
  ClubedascolecionadorasDashboardRouteImport.update({
    id: '/clubedascolecionadoras/_dashboard',
    path: '/clubedascolecionadoras',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubedascolecionadorasDashboardIndexRoute =
  ClubedascolecionadorasDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardTrocasRoute =
  ClubedascolecionadorasDashboardTrocasRouteImport.update({
    id: '/trocas',
    path: '/trocas',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardRegistrosRoute =
  ClubedascolecionadorasDashboardRegistrosRouteImport.update({
    id: '/registros',
    path: '/registros',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardQuizRoute =
  ClubedascolecionadorasDashboardQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardMuralRoute =
  ClubedascolecionadorasDashboardMuralRouteImport.update({
    id: '/mural',
    path: '/mural',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardLojaRoute =
  ClubedascolecionadorasDashboardLojaRouteImport.update({
    id: '/loja',
    path: '/loja',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardDoarRoute =
  ClubedascolecionadorasDashboardDoarRouteImport.update({
    id: '/doar',
    path: '/doar',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardConfigRoute =
  ClubedascolecionadorasDashboardConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardCodigosRoute =
  ClubedascolecionadorasDashboardCodigosRouteImport.update({
    id: '/codigos',
    path: '/codigos',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasDashboardAlbumRoute =
  ClubedascolecionadorasDashboardAlbumRouteImport.update({
    id: '/album',
    path: '/album',
    getParentRoute: () => ClubedascolecionadorasDashboardRoute,
  } as any)
const ClubedascolecionadorasAlbumUIdRoute =
  ClubedascolecionadorasAlbumUIdRouteImport.update({
    id: '/clubedascolecionadoras/album/u/$id',
    path: '/clubedascolecionadoras/album/u/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubedascolecionadoras': typeof ClubedascolecionadorasDashboardRouteWithChildren
  '/clubedascolecionadoras/confirmar-email': typeof ClubedascolecionadorasConfirmarEmailRoute
  '/clubedascolecionadoras/login': typeof ClubedascolecionadorasLoginRoute
  '/clubedascolecionadoras/signup': typeof ClubedascolecionadorasSignupRoute
  '/u/$id': typeof UIdRoute
  '/clubedascolecionadoras/album': typeof ClubedascolecionadorasDashboardAlbumRoute
  '/clubedascolecionadoras/codigos': typeof ClubedascolecionadorasDashboardCodigosRoute
  '/clubedascolecionadoras/config': typeof ClubedascolecionadorasDashboardConfigRoute
  '/clubedascolecionadoras/doar': typeof ClubedascolecionadorasDashboardDoarRoute
  '/clubedascolecionadoras/loja': typeof ClubedascolecionadorasDashboardLojaRoute
  '/clubedascolecionadoras/mural': typeof ClubedascolecionadorasDashboardMuralRoute
  '/clubedascolecionadoras/quiz': typeof ClubedascolecionadorasDashboardQuizRoute
  '/clubedascolecionadoras/registros': typeof ClubedascolecionadorasDashboardRegistrosRoute
  '/clubedascolecionadoras/trocas': typeof ClubedascolecionadorasDashboardTrocasRoute
  '/clubedascolecionadoras/': typeof ClubedascolecionadorasDashboardIndexRoute
  '/clubedascolecionadoras/album/u/$id': typeof ClubedascolecionadorasAlbumUIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubedascolecionadoras/confirmar-email': typeof ClubedascolecionadorasConfirmarEmailRoute
  '/clubedascolecionadoras/login': typeof ClubedascolecionadorasLoginRoute
  '/clubedascolecionadoras/signup': typeof ClubedascolecionadorasSignupRoute
  '/u/$id': typeof UIdRoute
  '/clubedascolecionadoras/album': typeof ClubedascolecionadorasDashboardAlbumRoute
  '/clubedascolecionadoras/codigos': typeof ClubedascolecionadorasDashboardCodigosRoute
  '/clubedascolecionadoras/config': typeof ClubedascolecionadorasDashboardConfigRoute
  '/clubedascolecionadoras/doar': typeof ClubedascolecionadorasDashboardDoarRoute
  '/clubedascolecionadoras/loja': typeof ClubedascolecionadorasDashboardLojaRoute
  '/clubedascolecionadoras/mural': typeof ClubedascolecionadorasDashboardMuralRoute
  '/clubedascolecionadoras/quiz': typeof ClubedascolecionadorasDashboardQuizRoute
  '/clubedascolecionadoras/registros': typeof ClubedascolecionadorasDashboardRegistrosRoute
  '/clubedascolecionadoras/trocas': typeof ClubedascolecionadorasDashboardTrocasRoute
  '/clubedascolecionadoras': typeof ClubedascolecionadorasDashboardIndexRoute
  '/clubedascolecionadoras/album/u/$id': typeof ClubedascolecionadorasAlbumUIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clubedascolecionadoras/_dashboard': typeof ClubedascolecionadorasDashboardRouteWithChildren
  '/clubedascolecionadoras/confirmar-email': typeof ClubedascolecionadorasConfirmarEmailRoute
  '/clubedascolecionadoras/login': typeof ClubedascolecionadorasLoginRoute
  '/clubedascolecionadoras/signup': typeof ClubedascolecionadorasSignupRoute
  '/u/$id': typeof UIdRoute
  '/clubedascolecionadoras/_dashboard/album': typeof ClubedascolecionadorasDashboardAlbumRoute
  '/clubedascolecionadoras/_dashboard/codigos': typeof ClubedascolecionadorasDashboardCodigosRoute
  '/clubedascolecionadoras/_dashboard/config': typeof ClubedascolecionadorasDashboardConfigRoute
  '/clubedascolecionadoras/_dashboard/doar': typeof ClubedascolecionadorasDashboardDoarRoute
  '/clubedascolecionadoras/_dashboard/loja': typeof ClubedascolecionadorasDashboardLojaRoute
  '/clubedascolecionadoras/_dashboard/mural': typeof ClubedascolecionadorasDashboardMuralRoute
  '/clubedascolecionadoras/_dashboard/quiz': typeof ClubedascolecionadorasDashboardQuizRoute
  '/clubedascolecionadoras/_dashboard/registros': typeof ClubedascolecionadorasDashboardRegistrosRoute
  '/clubedascolecionadoras/_dashboard/trocas': typeof ClubedascolecionadorasDashboardTrocasRoute
  '/clubedascolecionadoras/_dashboard/': typeof ClubedascolecionadorasDashboardIndexRoute
  '/clubedascolecionadoras/album/u/$id': typeof ClubedascolecionadorasAlbumUIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clubedascolecionadoras'
    | '/clubedascolecionadoras/confirmar-email'
    | '/clubedascolecionadoras/login'
    | '/clubedascolecionadoras/signup'
    | '/u/$id'
    | '/clubedascolecionadoras/album'
    | '/clubedascolecionadoras/codigos'
    | '/clubedascolecionadoras/config'
    | '/clubedascolecionadoras/doar'
    | '/clubedascolecionadoras/loja'
    | '/clubedascolecionadoras/mural'
    | '/clubedascolecionadoras/quiz'
    | '/clubedascolecionadoras/registros'
    | '/clubedascolecionadoras/trocas'
    | '/clubedascolecionadoras/'
    | '/clubedascolecionadoras/album/u/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clubedascolecionadoras/confirmar-email'
    | '/clubedascolecionadoras/login'
    | '/clubedascolecionadoras/signup'
    | '/u/$id'
    | '/clubedascolecionadoras/album'
    | '/clubedascolecionadoras/codigos'
    | '/clubedascolecionadoras/config'
    | '/clubedascolecionadoras/doar'
    | '/clubedascolecionadoras/loja'
    | '/clubedascolecionadoras/mural'
    | '/clubedascolecionadoras/quiz'
    | '/clubedascolecionadoras/registros'
    | '/clubedascolecionadoras/trocas'
    | '/clubedascolecionadoras'
    | '/clubedascolecionadoras/album/u/$id'
  id:
    | '__root__'
    | '/'
    | '/clubedascolecionadoras/_dashboard'
    | '/clubedascolecionadoras/confirmar-email'
    | '/clubedascolecionadoras/login'
    | '/clubedascolecionadoras/signup'
    | '/u/$id'
    | '/clubedascolecionadoras/_dashboard/album'
    | '/clubedascolecionadoras/_dashboard/codigos'
    | '/clubedascolecionadoras/_dashboard/config'
    | '/clubedascolecionadoras/_dashboard/doar'
    | '/clubedascolecionadoras/_dashboard/loja'
    | '/clubedascolecionadoras/_dashboard/mural'
    | '/clubedascolecionadoras/_dashboard/quiz'
    | '/clubedascolecionadoras/_dashboard/registros'
    | '/clubedascolecionadoras/_dashboard/trocas'
    | '/clubedascolecionadoras/_dashboard/'
    | '/clubedascolecionadoras/album/u/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubedascolecionadorasDashboardRoute: typeof ClubedascolecionadorasDashboardRouteWithChildren
  ClubedascolecionadorasConfirmarEmailRoute: typeof ClubedascolecionadorasConfirmarEmailRoute
  ClubedascolecionadorasLoginRoute: typeof ClubedascolecionadorasLoginRoute
  ClubedascolecionadorasSignupRoute: typeof ClubedascolecionadorasSignupRoute
  UIdRoute: typeof UIdRoute
  ClubedascolecionadorasAlbumUIdRoute: typeof ClubedascolecionadorasAlbumUIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubedascolecionadoras/signup': {
      id: '/clubedascolecionadoras/signup'
      path: '/clubedascolecionadoras/signup'
      fullPath: '/clubedascolecionadoras/signup'
      preLoaderRoute: typeof ClubedascolecionadorasSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubedascolecionadoras/login': {
      id: '/clubedascolecionadoras/login'
      path: '/clubedascolecionadoras/login'
      fullPath: '/clubedascolecionadoras/login'
      preLoaderRoute: typeof ClubedascolecionadorasLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubedascolecionadoras/confirmar-email': {
      id: '/clubedascolecionadoras/confirmar-email'
      path: '/clubedascolecionadoras/confirmar-email'
      fullPath: '/clubedascolecionadoras/confirmar-email'
      preLoaderRoute: typeof ClubedascolecionadorasConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubedascolecionadoras/_dashboard': {
      id: '/clubedascolecionadoras/_dashboard'
      path: '/clubedascolecionadoras'
      fullPath: '/clubedascolecionadoras'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubedascolecionadoras/_dashboard/': {
      id: '/clubedascolecionadoras/_dashboard/'
      path: '/'
      fullPath: '/clubedascolecionadoras/'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardIndexRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/trocas': {
      id: '/clubedascolecionadoras/_dashboard/trocas'
      path: '/trocas'
      fullPath: '/clubedascolecionadoras/trocas'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardTrocasRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/registros': {
      id: '/clubedascolecionadoras/_dashboard/registros'
      path: '/registros'
      fullPath: '/clubedascolecionadoras/registros'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardRegistrosRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/quiz': {
      id: '/clubedascolecionadoras/_dashboard/quiz'
      path: '/quiz'
      fullPath: '/clubedascolecionadoras/quiz'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardQuizRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/mural': {
      id: '/clubedascolecionadoras/_dashboard/mural'
      path: '/mural'
      fullPath: '/clubedascolecionadoras/mural'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardMuralRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/loja': {
      id: '/clubedascolecionadoras/_dashboard/loja'
      path: '/loja'
      fullPath: '/clubedascolecionadoras/loja'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardLojaRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/doar': {
      id: '/clubedascolecionadoras/_dashboard/doar'
      path: '/doar'
      fullPath: '/clubedascolecionadoras/doar'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardDoarRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/config': {
      id: '/clubedascolecionadoras/_dashboard/config'
      path: '/config'
      fullPath: '/clubedascolecionadoras/config'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardConfigRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/codigos': {
      id: '/clubedascolecionadoras/_dashboard/codigos'
      path: '/codigos'
      fullPath: '/clubedascolecionadoras/codigos'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardCodigosRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/_dashboard/album': {
      id: '/clubedascolecionadoras/_dashboard/album'
      path: '/album'
      fullPath: '/clubedascolecionadoras/album'
      preLoaderRoute: typeof ClubedascolecionadorasDashboardAlbumRouteImport
      parentRoute: typeof ClubedascolecionadorasDashboardRoute
    }
    '/clubedascolecionadoras/album/u/$id': {
      id: '/clubedascolecionadoras/album/u/$id'
      path: '/clubedascolecionadoras/album/u/$id'
      fullPath: '/clubedascolecionadoras/album/u/$id'
      preLoaderRoute: typeof ClubedascolecionadorasAlbumUIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClubedascolecionadorasDashboardRouteChildren {
  ClubedascolecionadorasDashboardAlbumRoute: typeof ClubedascolecionadorasDashboardAlbumRoute
  ClubedascolecionadorasDashboardCodigosRoute: typeof ClubedascolecionadorasDashboardCodigosRoute
  ClubedascolecionadorasDashboardConfigRoute: typeof ClubedascolecionadorasDashboardConfigRoute
  ClubedascolecionadorasDashboardDoarRoute: typeof ClubedascolecionadorasDashboardDoarRoute
  ClubedascolecionadorasDashboardLojaRoute: typeof ClubedascolecionadorasDashboardLojaRoute
  ClubedascolecionadorasDashboardMuralRoute: typeof ClubedascolecionadorasDashboardMuralRoute
  ClubedascolecionadorasDashboardQuizRoute: typeof ClubedascolecionadorasDashboardQuizRoute
  ClubedascolecionadorasDashboardRegistrosRoute: typeof ClubedascolecionadorasDashboardRegistrosRoute
  ClubedascolecionadorasDashboardTrocasRoute: typeof ClubedascolecionadorasDashboardTrocasRoute
  ClubedascolecionadorasDashboardIndexRoute: typeof ClubedascolecionadorasDashboardIndexRoute
}

const ClubedascolecionadorasDashboardRouteChildren: ClubedascolecionadorasDashboardRouteChildren =
  {
    ClubedascolecionadorasDashboardAlbumRoute:
      ClubedascolecionadorasDashboardAlbumRoute,
    ClubedascolecionadorasDashboardCodigosRoute:
      ClubedascolecionadorasDashboardCodigosRoute,
    ClubedascolecionadorasDashboardConfigRoute:
      ClubedascolecionadorasDashboardConfigRoute,
    ClubedascolecionadorasDashboardDoarRoute:
      ClubedascolecionadorasDashboardDoarRoute,
    ClubedascolecionadorasDashboardLojaRoute:
      ClubedascolecionadorasDashboardLojaRoute,
    ClubedascolecionadorasDashboardMuralRoute:
      ClubedascolecionadorasDashboardMuralRoute,
    ClubedascolecionadorasDashboardQuizRoute:
      ClubedascolecionadorasDashboardQuizRoute,
    ClubedascolecionadorasDashboardRegistrosRoute:
      ClubedascolecionadorasDashboardRegistrosRoute,
    ClubedascolecionadorasDashboardTrocasRoute:
      ClubedascolecionadorasDashboardTrocasRoute,
    ClubedascolecionadorasDashboardIndexRoute:
      ClubedascolecionadorasDashboardIndexRoute,
  }

const ClubedascolecionadorasDashboardRouteWithChildren =
  ClubedascolecionadorasDashboardRoute._addFileChildren(
    ClubedascolecionadorasDashboardRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubedascolecionadorasDashboardRoute:
    ClubedascolecionadorasDashboardRouteWithChildren,
  ClubedascolecionadorasConfirmarEmailRoute:
    ClubedascolecionadorasConfirmarEmailRoute,
  ClubedascolecionadorasLoginRoute: ClubedascolecionadorasLoginRoute,
  ClubedascolecionadorasSignupRoute: ClubedascolecionadorasSignupRoute,
  UIdRoute: UIdRoute,
  ClubedascolecionadorasAlbumUIdRoute: ClubedascolecionadorasAlbumUIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
