-- Alinha a tabela public.stickers com o seed oficial de 360 figurinhas.
-- Seguro para rodar em bancos existentes: atualiza metadados sem mexer no inventário das usuárias.

alter table public.stickers
  add column if not exists category text;

insert into public.stickers (number, slug, name, author, type, cover_url, amazon_url, category)
values
  (1, 'amor-fati', 'Amor Fati', 'G.B. Baldassari', 'quiz', 'amor-fati.jpg', 'https://link.amazon/B04QsFxvd', 'quiz'),
  (2, 'cupidos-nao-se-apaixonam', 'Cupidos não se apaixonam', 'Clara Alves', 'quiz', 'cupidos-nao-se-apaixonam.jpg', 'https://link.amazon/B0aMON6CM', 'quiz'),
  (3, 'eu-minha-crush-e-minha-irma', 'Eu, minha crush e minha irmã', 'Bia Crespo', 'quiz', 'eu-minha-crush-e-minha-irma.jpg', 'https://link.amazon/B0gHZl9q6', 'quiz'),
  (4, 'liz-flores-e-uma-farsa', 'Liz Flores é uma farsa', 'Victoria Mendes', 'quiz', 'liz-flores-e-uma-farsa.jpg', 'https://link.amazon/B05Ayf9iA', 'quiz'),
  (5, 'segundo-cliche', 'Segundo Clichê (Frutaverso Livro 1)', 'Line Cunha', 'quiz', 'segundo-cliche.jpg', 'https://link.amazon/B0hSXOXJx', 'quiz'),
  (6, 'desejos-ocultos-das-violetas', 'Desejos Ocultos das Violetas', 'Mariana Rosa', 'quiz', 'desejos-ocultos-das-violetas.jpg', 'https://link.amazon/B0iwzpQsy', 'quiz'),
  (7, 'o-casamento', 'O Casamento', 'Ju Mesquita', 'quiz', 'o-casamento.jpg', 'https://link.amazon/B07RMb9et', 'quiz'),
  (8, 'como-não-se-apaixonar', 'Como (não) se apaixonar', 'D. Barreto', 'quiz', 'como-não-se-apaixonar.jpg', 'https://link.amazon/B012VqDsq', 'quiz'),
  (9, 'ela-e-mais-do-que-voce-imagina', 'Ela é mais do que você imagina', 'V.S. Vilela', 'quiz', 'ela-e-mais-do-que-voce-imagina.jpg', 'https://link.amazon/B0iyUjTD5', 'quiz'),
  (10, 'nao-conta-pra-ela', '(Não) conta pra ela', 'Karoline Mandu', 'quiz', 'nao-conta-pra-ela.jpg', 'https://link.amazon/B0ihxjwaN', 'quiz'),
  (11, 'opostas-em-guerra', 'Opostas em Guerra', 'Sarah Oliveira', 'quiz', 'opostas-em-guerra.jpg', 'https://link.amazon/B0aB3FcnO', 'quiz'),
  (12, 'em-todas-as-gotas-de-chuva', 'Em todas as gotas de chuva', 'Englantine', 'quiz', 'em-todas-as-gotas-de-chuva.jpg', 'https://link.amazon/B03fZPEe3', 'quiz'),
  (13, 'colegas-de-quarto', 'Colegas de Quarto', 'Marina Basso', 'quiz', 'colegas-de-quarto.jpg', 'https://link.amazon/B04Li75y5', 'quiz'),
  (14, 'imensuravel-uma-nova-chance-para-amar', 'Imensurável: Uma nova chance para amar', 'Zey Shelsea', 'quiz', 'imensuravel-uma-nova-chance-para-amar.jpg', 'https://link.amazon/B08HyxVyX', 'quiz'),
  (15, 'georgia-rose', 'Georgia Rose: Segredos de Florença', 'Victoria Moon', 'quiz', 'georgia-rose.jpg', 'https://link.amazon/B0cgvqwcH', 'quiz'),
  (16, 'a-garota-do-topo', 'A Garota do Topo', 'Helena Nolasco', 'quiz', 'a-garota-do-topo.jpg', 'https://link.amazon/B0aCQG15A', 'quiz'),
  (17, 'nao-e-so-de-amor-que-eu-sei-falar', 'Não é só de amor que eu sei falar', 'Yasmim Mahmud Kader', 'quiz', 'nao-e-so-de-amor-que-eu-sei-falar.jpg', 'https://link.amazon/B08XPOF7V', 'quiz'),
  (18, 'os-segredos-que-contei-ao-oceano', 'Os Segredos Que Contei Ao Oceano', 'Camilla Giordanno', 'quiz', 'os-segredos-que-contei-ao-oceano.jpg', 'https://link.amazon/B01StrwX7', 'quiz'),
  (19, 'opostos-complementares', 'Opostos Complementares (Opostos Co. Livro 1)', 'Fernanda V.', 'quiz', 'opostos-complementares.jpg', 'https://link.amazon/B0fTuoQV8', 'quiz'),
  (20, 'cancao-dos-ossos', 'Canção dos Ossos', 'Giu Domingues', 'quiz', 'cancao-dos-ossos.jpg', 'https://link.amazon/B0aYElcl2', 'quiz'),
  (21, 'os-sete-maridos-de-evelyn-hugo', 'Os sete maridos de Evelyn Hugo', 'Taylor Jenkins Reid', 'sorteio', 'os-sete-maridos-de-evelyn-hugo.jpg', 'https://link.amazon/B0ci4Vbq1', 'sorteio'),
  (22, 'delilah-green-nao-esta-nem-ai', 'Delilah Green não está nem aí (Bright Falls)', 'Ashley Herring Blake', 'sorteio', 'delilah-green-nao-esta-nem-ai.jpg', 'https://link.amazon/B04jA353t', 'sorteio'),
  (23, 'pressagios-do-amor', 'Presságios do amor', 'Alexandria Bellefleur', 'sorteio', 'pressagios-do-amor.jpg', 'https://link.amazon/B056W8BF4', 'sorteio'),
  (24, 'fortuna-e- ascensao', 'Fortuna & Ascensão', 'Marcella M.', 'sorteio', 'fortuna-e- ascensao.jpg', 'https://link.amazon/B0aopido8', 'sorteio'),
  (25, 'o-amor-nao-e-obvio', 'O amor não é óbvio', 'Elayne Baeta', 'sorteio', 'o-amor-nao-e-obvio.jpg', 'https://link.amazon/B0cuzA7YO', 'sorteio'),
  (26, 'sementes-podres', 'Sementes Podres', 'Debora Carvalho', 'sorteio', 'sementes-podres.jpg', 'https://link.amazon/B057ruPlZ', 'sorteio'),
  (27, 'ice-quinn', 'Ice Quinn', 'Carol Barra', 'sorteio', 'ice-quinn.jpg', 'https://link.amazon/B02qznLoM', 'sorteio'),
  (28, 'salik-amor-e-ruina', 'Salik: Amor & Ruína', 'Bia R.D. Ramos', 'sorteio', 'salik-amor-e-ruina.jpg', 'https://link.amazon/B0bBabHzi', 'sorteio'),
  (29, 'alem-das-cameras', 'Além das Câmeras', 'Gina Milbradt', 'sorteio', 'alem-das-cameras.jpg', 'https://link.amazon/B0iQ32vab', 'sorteio'),
  (30, 'skips-drops', 'Skips, Drops', 'Tessa Reis', 'sorteio', 'skips-drops.jpg', 'https://link.amazon/B01e9AESA', 'sorteio'),
  (31, 'sem-palavra-de-seguranca', 'Sem palavra de segurança', 'Leila Venturini', 'sorteio', 'sem-palavra-de-seguranca.jpg', 'https://link.amazon/B00QZrBwV', 'sorteio'),
  (32, 'aguas-de-marco', 'Águas de Março', 'Gisele Carvalho e Hannah Kaiser', 'sorteio', 'aguas-de-marco.jpg', 'https://link.amazon/B01qjR1Ii', 'sorteio'),
  (33, 'os-4-espelhos', 'Os 4 Espelhos', 'Marina Porteclis', 'sorteio', 'os-4-espelhos.jpg', 'https://link.amazon/B0bPXOC1h', 'sorteio'),
  (34, 'um-traco-ate-voce', 'Um traço até você', 'Olívia Pilar', 'sorteio', 'um-traco-ate-voce.jpg', 'https://link.amazon/B03O8W0R6', 'sorteio'),
  (35, 'herdeiras-de-pedra-e-ar', 'Herdeiras de pedra e ar', 'Mar Freitas', 'sorteio', 'herdeiras-de-pedra-e-ar.jpg', 'https://link.amazon/B0hsZOXsN', 'sorteio'),
  (36, 'ultima-parada', 'Última parada', 'Casey McQuiston', 'sorteio', 'ultima-parada.jpg', 'https://link.amazon/B03JavGBa', 'sorteio'),
  (37, 'vitrine', 'Vitrine: Um contrato pode mudar tudo', 'Ingrid Paranhos', 'sorteio', 'vitrine.jpg', 'https://link.amazon/B06XYVmBg', 'sorteio'),
  (38, 'as-vantagens-de-ser-voce', 'As vantagens de ser você', 'Ray Tavares', 'sorteio', 'as-vantagens-de-ser-voce.jpg', 'https://link.amazon/B0g3Un09w', 'sorteio'),
  (39, 'o-nome-dela-e-sophia', 'O Nome Dela é Sophia', 'Vanessa Freitas', 'sorteio', 'o-nome-dela-e-sophia.jpg', 'https://link.amazon/B0h1b3T05', 'sorteio'),
  (40, 'galaxia-desconhecida', 'Galáxia Desconhecida', 'Raquel Alves', 'sorteio', 'galaxia-desconhecida.jpg', 'https://link.amazon/B02X3X0ul', 'sorteio'),
  (41, 'ela-fica-com-a-garota', 'Ela fica com a garota', 'Rachael Lippincott e Alyson Derrick', 'sorteio', 'ela-fica-com-a-garota.jpg', 'https://link.amazon/B04PSvTjs', 'sorteio'),
  (42, 'borboletas-da-morte', 'Borboletas da Morte', 'Lari Alcantara', 'sorteio', 'borboletas-da-morte.jpg', 'https://link.amazon/B02OJFJgm', 'sorteio'),
  (43, 'alem-do-silencio', 'Além do Silêncio', 'Jéssica Batista', 'sorteio', 'alem-do-silencio.jpg', 'https://link.amazon/B0cf0CiCx', 'sorteio'),
  (44, 'que-a-melhor-mordida-venca', 'Que a melhor mordida vença', 'Rina Rodriguez', 'sorteio', 'que-a-melhor-mordida-venca.jpg', 'https://link.amazon/B08nVTXCG', 'sorteio'),
  (45, 'cerejas-do-inferno', 'Cerejas do inferno', 'Thais Boito', 'sorteio', 'cerejas-do-inferno.jpg', 'https://link.amazon/B07bmVSa1', 'sorteio'),
  (46, 'xeque-mate', 'Xeque-Mate', 'Evelin Sousa', 'sorteio', 'xeque-mate.jpg', 'https://link.amazon/B0gB54D3g', 'sorteio'),
  (47, 'a-beira-de-nos', 'À Beira de Nós', 'Laila Zago', 'sorteio', 'a-beira-de-nos.jpg', 'https://link.amazon/B08k93R1X', 'sorteio'),
  (48, 'garota-de-programa', 'Garota de Programa', 'Rebecca Nobre', 'sorteio', 'garota-de-programa.jpg', 'https://link.amazon/B0cCEh252', 'sorteio'),
  (49, 'dona-do-meu-pecado-ruina', 'Dona do meu pecado', 'Fernanda Moser', 'sorteio', 'dona-do-meu-pecado-ruina.jpg', 'https://link.amazon/B0a1E9oWd', 'sorteio'),
  (50, 'overdrive', 'Overdrive', 'Agatha Menezes', 'sorteio', 'overdrive.jpg', 'https://link.amazon/B0cggcJZt', 'sorteio'),
  (51, 'astrid-parker-nunca-falha', 'Astrid Parker nunca falha (Bright Falls)', 'Ashley Herring Blake', 'sorteio', 'astrid-parker-nunca-falha.jpg', 'https://link.amazon/B0b2BXX3e', 'sorteio'),
  (52, 'iris-kelly-nao-namora', 'Iris Kelly não namora (Bright Falls)', 'Ashley Herring Blake', 'sorteio', 'iris-kelly-nao-namora.jpg', 'https://link.amazon/B0gv8pOcI', 'sorteio'),
  (53, 'so-por-um-verao', 'Só por um verão (Família Lancelloti Livro 1)', 'G.B. Baldassari', 'sorteio', 'so-por-um-verao.jpg', 'https://link.amazon/B013Gv9HT', 'sorteio'),
  (54, 'de-repente-namoradas', '⁠De Repente, Namoradas (Família Lancellotti Livro 2)', 'G.B. Baldassari', 'sorteio', 'de-repente-namoradas.jpg', 'https://link.amazon/B0fotnKAJ', 'sorteio'),
  (55, 'paixao-platonica', 'Paixão platônica', 'Liliane Reis', 'sorteio', 'paixao-platonica.jpg', 'https://link.amazon/B01efxW70', 'sorteio'),
  (56, 'entre-livros-e-fios-dourados', '⁠Entre Livros e Fios Dourados', 'Lolline Huntar''z', 'sorteio', 'entre-livros-e-fios-dourados.jpg', 'https://link.amazon/B07of9W0q', 'sorteio'),
  (57, 'o-abanar-do-amor', 'O Abanar do Amor', 'Nicoly Pacheco', 'sorteio', 'o-abanar-do-amor.jpg', 'https://link.amazon/B0f4HvhKM', 'sorteio'),
  (58, 'a-melhor-amiga-do-meu-namorado', 'A melhor amiga do meu namorado', 'Carol Cara', 'sorteio', 'a-melhor-amiga-do-meu-namorado.jpg', 'https://link.amazon/B0c9m2QpI', 'sorteio'),
  (59, 'terceiro-croqui', 'Terceiro Croqui (Frutaverso Livro 2)', 'Line Cunha', 'sorteio', 'terceiro-croqui.jpg', 'https://link.amazon/B0hkj4k39', 'sorteio'),
  (60, 'operacao-conves', 'Operação Convés (Frutaverso Livro 3)', 'Line Cunha', 'sorteio', 'operacao-conves.jpg', 'https://link.amazon/B08Pn5mVJ', 'sorteio'),
  (61, 'princesa-apaixonada', '⁠Princesa apaixonada', 'Clare Lydon', 'sorteio', 'princesa-apaixonada.jpg', 'https://link.amazon/B0gW0gLh8', 'sorteio'),
  (62, 'garotas-de-cristal', 'Garotas de Cristal', 'Nico Baladore', 'sorteio', 'garotas-de-cristal.jpg', 'https://link.amazon/B05zoRLDL', 'sorteio'),
  (63, 'maes-por-acidente', '⁠Mães por Acidente', 'Ju Mesquita', 'sorteio', 'maes-por-acidente.jpg', 'https://link.amazon/B04vBGeuo', 'sorteio'),
  (64, 'cartas-para-pior-garota-do-mundo-ps-eu-te-odeio', '⁠Cartas Para Pior Garota do Mundo: PS: Eu te Odeio', 'Evyn Mota', 'sorteio', 'cartas-para-pior-garota-do-mundo-ps-eu-te-odeio.jpg', 'https://link.amazon/B04YJcE8A', 'sorteio'),
  (65, 'como-seduzir-a-novata', 'Como Seduzir A Novata', 'Helena Vieira', 'sorteio', 'como-seduzir-a-novata.jpg', 'https://link.amazon/B0cFE1NJH', 'sorteio'),
  (66, 'clausula-da-paixao', 'Cláusula da Paixão', 'Madu Oliveira', 'sorteio', 'clausula-da-paixao.jpg', 'https://link.amazon/B08x079rq', 'sorteio'),
  (67, 'patinando-ate-voce', 'Patinando até Você', 'Agatha Menezes', 'sorteio', 'patinando-ate-voce.jpg', 'https://link.amazon/B00NunQDy', 'sorteio'),
  (68, 'proibido-se-apaixonar-de-novo', 'Proibido se apaixonar de novo', 'V.S. Vilela', 'sorteio', 'proibido-se-apaixonar-de-novo.jpg', 'https://link.amazon/B05f82cDM', 'sorteio'),
  (69, 'a-filha-proibida-do-meu-chefe', 'A Filha Proibida do Meu Chefe', 'Lorena Rodrigues', 'sorteio', 'a-filha-proibida-do-meu-chefe.jpg', 'https://link.amazon/B0giLWGbJ', 'sorteio'),
  (70, 'volte-pra-superficie', 'Volte pra Superfície', 'Victoria Mendes', 'sorteio', 'volte-pra-superficie.jpg', 'https://link.amazon/B03aE147Z', 'sorteio'),
  (71, 'nao-somos-melhores-amigas', '⁠Não somos melhores amigas', 'Vanessa Airalis', 'sorteio', 'nao-somos-melhores-amigas.jpg', 'https://link.amazon/B0dSLFTN8', 'sorteio'),
  (72, 'enfim-esposas', 'Enfim, esposas', 'Vanessa Airalis', 'sorteio', 'enfim-esposas.jpg', 'https://link.amazon/B05wzI32N', 'sorteio'),
  (73, 'opostos-concomitantes', 'Opostos Concomitantes (Opostos Co. Livro 2)', 'Fernanda V.', 'sorteio', 'opostos-concomitantes.jpg', 'https://link.amazon/B0hA8MPQK', 'sorteio'),
  (74, 'opostos-contingentes', '⁠Opostos Contingentes (Opostos Co. Livro 3)', 'Fernanda V.', 'sorteio', 'opostos-contingentes.jpg', 'https://link.amazon/B08V6ouSb', 'sorteio'),
  (75, 'alianca-em-campo-ganhando-o-jogo', '⁠Aliança em Campo: Ganhando o Jogo', 'Nick Martins', 'sorteio', 'alianca-em-campo-ganhando-o-jogo.jpg', 'https://link.amazon/B09z94Ff9', 'sorteio'),
  (76, 'a-sociedade-de-eva-parte-1', '⁠A Sociedade de Eva: Parte I : a dança', 'Mia Perdu', 'sorteio', 'a-sociedade-de-eva-parte-1.jpg', 'https://link.amazon/B0bDngD5Q', 'sorteio'),
  (77, 'a-sociedade-de-eva-parte-2', '⁠A Sociedade de Eva: Parte II: a queda', 'Mia Perdu', 'sorteio', 'a-sociedade-de-eva-parte-2.jpg', 'https://link.amazon/B02bWAANJ', 'sorteio'),
  (78, 'medusa', 'Medusa', 'Ana França', 'sorteio', 'medusa.jpg', 'https://link.amazon/B0fQVqGkL', 'sorteio'),
  (79, 'ultimo-romance', '⁠Último Romance', 'Thais Rodrigues', 'sorteio', 'ultimo-romance.jpg', 'https://link.amazon/B08Ongwam', 'sorteio'),
  (80, 'monte-belalis', '⁠Monte Belalis', 'Victoria Moon', 'sorteio', 'monte-belalis.jpg', 'https://link.amazon/B0f3CGMWR', 'sorteio'),
  (81, 'retrato-de-amor', '⁠Retrato de Amor', 'Pris Santiago', 'sorteio', 'retrato-de-amor.jpg', 'https://link.amazon/B0gxRAUJd', 'sorteio'),
  (82, 'uma-familia-ao-acaso', '⁠Uma família ao acaso', 'Débora Silva', 'sorteio', 'uma-familia-ao-acaso.jpg', 'https://link.amazon/B05AIsohv', 'sorteio'),
  (83, 'o-trono-de-jasmim', 'O trono de jasmim (Vol. 1 Os Reinos em Chamas)', 'Tasha Suri', 'sorteio', 'o-trono-de-jasmim.jpg', 'https://link.amazon/B071mr0uF', 'sorteio'),
  (84, 'o-cara-que-estou-a-fim-nao-e-um-cara-volume-1', '⁠O cara que estou a fim não é um cara?! - Volume 1', 'Sumiko Arai', 'sorteio', 'o-cara-que-estou-a-fim-nao-e-um-cara-volume-1.jpg', 'https://link.amazon/B05ebJnYN', 'sorteio'),
  (85, 'a-garota-do-mar', '⁠A garota do mar', 'Molly Knox Ostertag', 'sorteio', 'a-garota-do-mar.jpg', 'https://link.amazon/B0dqrP1PM', 'sorteio'),
  (86, 'girls-like-girls', '⁠Girls Like Girls', 'Hayley Kiyoko', 'sorteio', 'girls-like-girls.jpg', 'https://link.amazon/B0cRRvbYi', 'sorteio'),
  (87, 'full-shift', 'Full Shift: A transformação total', 'Jennifer Dugan', 'sorteio', 'full-shift.jpg', 'https://link.amazon/B0iXT6Xwp', 'sorteio'),
  (88, 'jardim-para-duas', '⁠Jardim para duas', 'Mazey Eddings', 'sorteio', 'jardim-para-duas.jpg', 'https://link.amazon/B0i5SQiYk', 'sorteio'),
  (89, 'imogen-obviamente', '⁠Imogen, obviamente', 'Becky Albertalli', 'sorteio', 'imogen-obviamente.jpg', 'https://link.amazon/B0aQp39A7', 'sorteio'),
  (90, 'ninguem-especial', '⁠Ninguém especial', 'Sophie Gonzales', 'sorteio', 'ninguem-especial.jpg', 'https://link.amazon/B0bXVQdha', 'sorteio'),
  (91, 'frases-1', 'Obcecada por mulheres fictícias', null, 'frase', 'frases-1.jpeg', null, 'frase'),
  (92, 'frases-2', 'Fã nº 1 de personagens sáficas trambiqueiras', null, 'frase', 'frases-2.jpeg', null, 'frase'),
  (93, 'frases-3', 'Me pergunte sobre meus livros sáficos favoritos', null, 'frase', 'frases-3.jpeg', null, 'frase'),
  (94, 'frases-4', 'Status: em relacionamento sério com várias personagens sáficas', null, 'frase', 'frases-4.jpeg', null, 'frase'),
  (95, 'frases-5', '0days 0hours 0minutes Since last falling in love with a fictional woman', null, 'frase', 'frases-5.jpeg', null, 'frase'),
  (96, 'ls-1', 'enemies to lovers', null, 'ls', 'ls-1.jpeg', null, 'ls'),
  (97, 'ls-2', 'friends to lovers', null, 'ls', 'ls-2.jpeg', null, 'ls'),
  (98, 'ls-3', 'só tem uma cama', null, 'ls', 'ls-3.jpeg', null, 'ls'),
  (99, 'ls-4', 'grumpy x sunshine', null, 'ls', 'ls-4.jpeg', null, 'ls'),
  (100, 'ls-5', 'found family', null, 'ls', 'ls-5.jpeg', null, 'ls'),
  (101, 'jogando-no-seu-time', 'Jogando no seu time', 'Meryl Wilsner', 'sorteio', 'jogando-no-seu-time.jpg', 'https://link.amazon/B004FAXiE', 'sorteio'),
  (102, 'matriz-em-risco', 'Matriz em risco', 'Evyn Mota', 'sorteio', 'matriz-em-risco.jpg', 'https://link.amazon/B00gOZSsC', 'sorteio'),
  (103, 'amelia-quem-me-dera', 'Amelia, quem me dera', 'Becky Albertalli', 'sorteio', 'amelia-quem-me-dera.jpg', 'https://link.amazon/B00jRU6en', 'sorteio'),
  (104, 'as-ultimas-sobreviventes', 'As últimas sobreviventes', 'Jennifer Dugan', 'sorteio', 'as-ultimas-sobreviventes.jpg', 'https://link.amazon/B00sk04xV', 'sorteio'),
  (105, 'querida-penelope', 'Querida Penelope', 'Arquelana', 'sorteio', 'querida-penelope.jpg', 'https://link.amazon/B00x4dO36', 'sorteio'),
  (106, 'lost-on-you-destinos-entrelacados-livro-1', 'Lost On You (Destinos Entrelaçados Livro 1)', 'Swyanne Rodriguez', 'sorteio', 'lost-on-you-destinos-entrelacados-livro-1.jpg', 'https://link.amazon/B00yLixQ5', 'sorteio'),
  (107, 'guia-do-namoro-falso', 'Guia do namoro falso', 'Adiba Jaigirdar', 'sorteio', 'guia-do-namoro-falso.jpg', 'https://link.amazon/B013QWJtA', 'sorteio'),
  (108, 'estrela-da-sorte', 'Estrela da sorte', 'Alexandria Bellefleur', 'sorteio', 'estrela-da-sorte.jpg', 'https://link.amazon/B017sbEx5', 'sorteio'),
  (109, 'o-coracao-envenenado', 'O coração envenenado', 'Kalynn Bayron', 'sorteio', 'o-coracao-envenenado.jpg', 'https://link.amazon/B01LazciY', 'sorteio'),
  (110, 'a-maldicao-da-casa-das-flores', 'A Maldição da Casa das Flores', 'Trang Thanh Tran', 'sorteio', 'a-maldicao-da-casa-das-flores.jpg', 'https://link.amazon/B01uqnsjO', 'sorteio'),
  (111, 'voce-vai-lembrar-de-mim', 'Você Vai Lembrar de Mim', 'G.B. Baldassari', 'sorteio', 'voce-vai-lembrar-de-mim.jpg', 'https://link.amazon/B01wtRi1n', 'sorteio'),
  (112, 'a-vida-secreta-de-isabela-esme', 'A vida secreta de Isabela Esme', 'Lis Selwyn', 'sorteio', 'a-vida-secreta-de-isabela-esme.jpg', 'https://link.amazon/B01zMQXG9', 'sorteio'),
  (113, 'duelo-de-damas', 'Duelo de Damas', 'Marina Basso', 'sorteio', 'duelo-de-damas.jpg', 'https://link.amazon/B02ClFU23', 'sorteio'),
  (114, 'se-ela-fosse-minha', 'Se ela fosse minha', 'Alison Cochrun', 'sorteio', 'se-ela-fosse-minha.jpg', 'https://link.amazon/B03bYluQY', 'sorteio'),
  (115, 'nao-importa-o-que-digam', 'Não importa o que digam', 'V.S. Vilela', 'sorteio', 'nao-importa-o-que-digam.jpg', 'https://link.amazon/B03IfxOSd', 'sorteio'),
  (116, 'uma-morte-tao-doce', 'Uma morte tão doce', 'Kayla Cottingham', 'sorteio', 'uma-morte-tao-doce.jpg', 'https://link.amazon/B03VCzIJQ', 'sorteio'),
  (117, 'atmosfera-uma-historia-de-amor', 'Atmosfera: Uma história de amor', 'Taylor Jenkins Reid', 'sorteio', 'atmosfera-uma-historia-de-amor.jpg', 'https://link.amazon/B044hiCpB', 'sorteio'),
  (118, 'beijos-com-sabor-de-verao', 'Beijos com sabor de verão', 'Vanessa Freitas', 'sorteio', 'beijos-com-sabor-de-verao.jpg', 'https://link.amazon/B0457CQJ8', 'sorteio'),
  (119, 'a-princesa-e-o-queijo-quente', 'A princesa e o queijo quente', 'Deya Muniz', 'sorteio', 'a-princesa-e-o-queijo-quente.jpg', 'https://link.amazon/B04fvsfP0', 'sorteio'),
  (120, 'a-lista-da-sorte', 'A lista da sorte', 'Rachael Lippincott', 'sorteio', 'a-lista-da-sorte.jpg', 'https://link.amazon/B04giCTKg', 'sorteio'),
  (121, 'o-retorno-de-saturno', 'O retorno de Saturno', 'Debora Carvalho', 'sorteio', 'o-retorno-de-saturno.jpg', 'https://link.amazon/B04jjrFZ6', 'sorteio'),
  (122, 'tinha-tudo-para-dar-errado', 'Tinha tudo para dar errado', 'G.B. Baldassari', 'sorteio', 'tinha-tudo-para-dar-errado.jpg', 'https://link.amazon/B053EF7n6', 'sorteio'),
  (123, 'wounds-o-veu-do-arcano', 'WOUNDS - O Véu do Arcano', 'Danda Odeleci', 'sorteio', 'wounds-o-veu-do-arcano.jpg', 'https://link.amazon/B05irfM29', 'sorteio'),
  (124, 'me-chame-quando-puder', 'Me Chame Quando Puder', 'Englantine', 'sorteio', 'me-chame-quando-puder.jpg', 'https://link.amazon/B061d4Npl', 'sorteio'),
  (125, 'oxe-baby', 'Oxe, baby', 'Elayne Baeta', 'sorteio', 'oxe-baby.jpg', 'https://link.amazon/B06gslCHJ', 'sorteio'),
  (126, 'orgulho-e-preconceito-e-nos-duas', 'Orgulho e preconceito e nós duas', 'Rachael Lippincott', 'sorteio', 'orgulho-e-preconceito-e-nos-duas.jpg', 'https://link.amazon/B06lgfoAS', 'sorteio'),
  (127, 'nas-entrelinhas', 'Nas Entrelinhas', 'Helena Nolasco', 'sorteio', 'nas-entrelinhas.jpg', 'https://link.amazon/B06oZJeT9', 'sorteio'),
  (128, 'foi-mal-cara', 'Foi mal, cara', 'Taleen Voskuni', 'sorteio', 'foi-mal-cara.jpg', 'https://link.amazon/B06P1M3DO', 'sorteio'),
  (129, 'um-amor-para-esquentar', 'Um Amor Para Esquentar', 'Emely Luiza Curcio', 'sorteio', 'um-amor-para-esquentar.jpg', 'https://link.amazon/B06zrEQDx', 'sorteio'),
  (130, 'a-um-sim-de-voce', 'A um sim de você', 'Zey Shelsea', 'sorteio', 'a-um-sim-de-voce.jpg', 'https://link.amazon/B072h9Z9A', 'sorteio'),
  (131, 'algumas-garotas-sao-assim', 'Algumas garotas são assim', 'Jennifer Dugan', 'sorteio', 'algumas-garotas-sao-assim.jpg', 'https://link.amazon/B07GGCdpC', 'sorteio'),
  (132, 'nunca-confie-em-uma-geminiana', 'Nunca confie em uma geminiana', 'Freja Nicole Woolf', 'sorteio', 'nunca-confie-em-uma-geminiana.jpg', 'https://link.amazon/B087f8UFd', 'sorteio'),
  (133, 'e-assim-que-se-perde-a-guerra-do-tempo', 'É assim que se perde a guerra do tempo', 'Amal El-Mohtar, Max Gladstone', 'sorteio', 'e-assim-que-se-perde-a-guerra-do-tempo.jpg', 'https://link.amazon/B088PHIey', 'sorteio'),
  (134, 'o-centro-de-todo-o-caos', 'O Centro de Todo o Caos', 'Marina Feijóo', 'sorteio', 'o-centro-de-todo-o-caos.jpg', 'https://link.amazon/B08abdNji', 'sorteio'),
  (135, 'presas', 'Presas', 'Debora Carvalho', 'sorteio', 'presas.jpg', 'https://link.amazon/B08aRNkvU', 'sorteio'),
  (136, 'lembre-se-de-nos', 'Lembre-se de nós', 'Alyson Derrick', 'sorteio', 'lembre-se-de-nos.jpg', 'https://link.amazon/B08B4fMHG', 'sorteio'),
  (137, 'fragmento', 'Fragmento', 'Andremis', 'sorteio', 'fragmento.jpg', 'https://link.amazon/B08fBJQ7s', 'sorteio'),
  (138, 'ela-nao-e-tudo-isso', 'Ela (não) é tudo isso', 'Carol Cara', 'sorteio', 'ela-nao-e-tudo-isso.jpg', 'https://link.amazon/B08Gtm70U', 'sorteio'),
  (139, 'todas-as-flores-que-eu-nao-te-dei', 'Todas as flores que eu não te dei', 'Sam Macedo', 'sorteio', 'todas-as-flores-que-eu-nao-te-dei.jpg', 'https://link.amazon/B08oXlode', 'sorteio'),
  (140, 'eu-que-nao-amo-voce', 'Eu que não amo você', 'Mar Freitas', 'sorteio', 'eu-que-nao-amo-voce.jpg', 'https://link.amazon/B090YhO0f', 'sorteio'),
  (141, 'as-bruxas-de-lugar-nenhum-entreveu-livro-1', 'As Bruxas de Lugar Nenhum: Entrevéu - Livro 1', 'Denise Flaibam', 'sorteio', 'as-bruxas-de-lugar-nenhum-entreveu-livro-1.jpg', 'https://link.amazon/B0970Ai94', 'sorteio'),
  (142, 'o-toque-do-seu-olhar', 'O toque do seu olhar', 'Liliane Reis', 'sorteio', 'o-toque-do-seu-olhar.jpg', 'https://link.amazon/B09qElCpn', 'sorteio'),
  (143, 'falha-critica-no-amor', 'Falha crítica no amor', 'Debora Carvalho', 'sorteio', 'falha-critica-no-amor.jpg', 'https://link.amazon/B09qVNH0I', 'sorteio'),
  (144, 'vai-sonhando-ramona-riley', 'Vai sonhando, Ramona Riley', 'Ashley Herring Blake', 'sorteio', 'vai-sonhando-ramona-riley.jpg', 'https://link.amazon/B09uHXAhw', 'sorteio'),
  (145, 'gideon', 'Gideon, a Nona: Saga do túmulo trancafiado', 'Tamsyn Muir', 'sorteio', 'gideon.jpg', 'https://link.amazon/B09ZMBaPF', 'sorteio'),
  (146, 'coisas-obvias-sobre-o-amor', 'Coisas óbvias sobre o amor', 'Elayne Baeta', 'sorteio', 'coisas-obvias-sobre-o-amor.jpg', 'https://link.amazon/B0a2dGI1r', 'sorteio'),
  (147, 'a-noite-passada-no-telegraph-club', 'A noite passada no Telegraph Club', 'Malinda Lo', 'sorteio', 'a-noite-passada-no-telegraph-club.jpg', 'https://link.amazon/B0a38jg62', 'sorteio'),
  (148, 'bala-no-alvo-dente-de-leao', 'Bala no Alvo, Dente de Leão', 'Giu Domigues', 'sorteio', 'bala-no-alvo-dente-de-leao.jpg', 'https://link.amazon/B0a519xy5', 'sorteio'),
  (149, 'esposa-de-mentira', 'Esposa de mentira', 'Zey Shelsea', 'sorteio', 'esposa-de-mentira.jpg', 'https://link.amazon/B0acYm4Gm', 'sorteio'),
  (150, 'a-ultima-cancao-de-amor', 'A última canção de amor', 'Kalie Holford', 'sorteio', 'a-ultima-cancao-de-amor.jpg', 'https://link.amazon/B0aDpQa8G', 'sorteio'),
  (151, 'yerba-buena', 'Yerba Buena', 'Nina LaCour', 'sorteio', 'yerba-buena.jpg', 'https://link.amazon/B0al0VN1Y', 'sorteio'),
  (152, 'ate-ela-dizer-sim', 'Até ela dizer sim', 'Laura Alves', 'sorteio', 'ate-ela-dizer-sim.jpg', 'https://link.amazon/B0aSdkpVi', 'sorteio'),
  (153, 'eles-odeiam-garotas-como-nos', 'Eles ODEIAM garotas como nós', 'Yasmim Mahmud Kader', 'sorteio', 'eles-odeiam-garotas-como-nos.jpg', 'https://link.amazon/B0aXvUN2g', 'sorteio'),
  (154, 'conectadas', 'Conectadas', 'Clara Alves', 'sorteio', 'conectadas.jpg', 'https://link.amazon/B0aXyVU6r', 'sorteio'),
  (155, 'belas-armadilhas', 'Belas Armadilhas', 'Carol Cara, Liliane Reis', 'sorteio', 'belas-armadilhas.jpg', 'https://link.amazon/B0b5LDyXp', 'sorteio'),
  (156, 'diario-de-bordo-de-uma-impostora', 'Diário de Bordo de uma Impostora', 'G.B. Baldassari', 'sorteio', 'diario-de-bordo-de-uma-impostora.jpg', 'https://link.amazon/B0b657M15', 'sorteio'),
  (157, 'os-perigos-de-brincar-com-fogo', 'Os perigos de brincar com fogo', 'Debora Carvalho', 'sorteio', 'os-perigos-de-brincar-com-fogo.jpg', 'https://link.amazon/B0bGSf5b9', 'sorteio'),
  (158, 'o-que-voce-faz-aqui-heather', 'O que você faz aqui, Heather?', 'Golden Faery', 'sorteio', 'o-que-voce-faz-aqui-heather.jpg', 'https://link.amazon/B0bn8NIEd', 'sorteio'),
  (159, 'shangrila', 'Shangrilá', 'Marina Porteclis', 'sorteio', 'shangrila.jpg', 'https://link.amazon/B0bNHwBMq', 'sorteio'),
  (160, 'sal', 'Sal', 'Tessa Reis', 'sorteio', 'sal.jpg', 'https://link.amazon/B0bweWrfy', 'sorteio'),
  (161, 'romance-real', 'Romance real', 'Clara Alves', 'sorteio', 'romance-real.jpg', 'https://link.amazon/B0bZG92Xs', 'sorteio'),
  (162, 'anotacoes-do-amor', 'Anotações do Amor', 'Emely Luiza Curcio', 'sorteio', 'anotacoes-do-amor.jpg', 'https://link.amazon/B0chIKAjX', 'sorteio'),
  (163, 'todo-tempo-do-mundo', 'Todo tempo do mundo', 'Lis Selwyn', 'sorteio', 'todo-tempo-do-mundo.jpg', 'https://link.amazon/B0cUENXVI', 'sorteio'),
  (164, 'feras-em-campo', 'Feras em campo', 'Luisa Landre', 'sorteio', 'feras-em-campo.jpg', 'https://link.amazon/B0cvHLL07', 'sorteio'),
  (165, 'tristeza', 'Tristeza', 'Vanessa Freitas', 'sorteio', 'tristeza.jpg', 'https://link.amazon/B0cZQsY8i', 'sorteio'),
  (166, 'me-encontre-a-meia-noite', 'Me encontre a meia-noite', 'Victoria Mendes', 'sorteio', 'me-encontre-a-meia-noite.jpg', 'https://link.amazon/B0dbORbGn', 'sorteio'),
  (167, 'segundo-ato', 'Segundo ato', 'Brenda Borges', 'sorteio', 'segundo-ato.jpg', 'https://link.amazon/B0dmDQ3T9', 'sorteio'),
  (168, 'sangue-fresco', 'Sangue fresco', 'Sasha Laurens', 'sorteio', 'sangue-fresco.jpg', 'https://link.amazon/B0dPkKsqc', 'sorteio'),
  (169, 'a-cortesa', 'A Cortesã', 'I.K. Prado', 'sorteio', 'a-cortesa.jpg', 'https://link.amazon/B0dVuaqLV', 'sorteio'),
  (170, 'o-outro-lado-do-paraiso', 'O Outro Lado do Paraíso', 'Ana França', 'sorteio', 'o-outro-lado-do-paraiso.jpg', 'https://link.amazon/B0e5DaHv6', 'sorteio'),
  (171, 'carmilla-a-vampira-de-karnstein', 'Carmilla: A Vampira de Karnstein', 'Sheridan Le Fanu', 'sorteio', 'carmilla-a-vampira-de-karnstein.jpg', 'https://link.amazon/B0e5vS7Te', 'sorteio'),
  (172, 'o-refugio-inquebravel-das-memorias-em-ruinas', 'O Refúgio Inquebrável das Memórias em Ruínas', 'Mariana Rosa', 'sorteio', 'o-refugio-inquebravel-das-memorias-em-ruinas.jpg', 'https://link.amazon/B0e6ndVLn', 'sorteio'),
  (173, 'memorias-de-um-amor-inesperado', 'Memórias de um amor inesperado', 'Ciara Smyth', 'sorteio', 'memorias-de-um-amor-inesperado.jpg', 'https://link.amazon/B0eGG3imi', 'sorteio'),
  (174, 'as-cartas', 'A(s) Carta(s)', 'Tori Lopes', 'sorteio', 'as-cartas.jpg', 'https://link.amazon/B0epn1oF0', 'sorteio'),
  (175, 'eu-beijei-shara-wheeler', 'Eu beijei Shara Wheeler', 'Casey McQuiston', 'sorteio', 'eu-beijei-shara-wheeler.jpg', 'https://link.amazon/B0eQVCiJE', 'sorteio'),
  (176, 'dentada', 'Dentada', 'Tessa Reis', 'sorteio', 'dentada.jpg', 'https://link.amazon/B0fBSXg8m', 'sorteio'),
  (177, 'algoritmos-de-uma-paixao', 'Algoritmos de Uma Paixão', 'Victoria Moon', 'sorteio', 'algoritmos-de-uma-paixao.jpg', 'https://link.amazon/B0fjU23X4', 'sorteio'),
  (178, 'enterrem-nossos-ossos-a-meia-noite', 'Enterrem nossos ossos à meia-noite', 'V. E. Schwab', 'sorteio', 'enterrem-nossos-ossos-a-meia-noite.jpg', 'https://link.amazon/B0g3ivw3f', 'sorteio'),
  (179, 'a-tentacao-da-ruina-obscura', 'A Tentação da Ruína Obscura', 'Mariana Rosa', 'sorteio', 'a-tentacao-da-ruina-obscura.jpg', 'https://link.amazon/B0g6gVZE3', 'sorteio'),
  (180, 'seis-vezes-em-que-a-gente-quase-ficou-e-uma-em-que-rolou', 'Seis vezes em que a gente quase ficou (e uma em que rolou)', 'Tess Sharpe', 'sorteio', 'seis-vezes-em-que-a-gente-quase-ficou-e-uma-em-que-rolou.jpg', 'https://link.amazon/B0g6KuMmX', 'sorteio'),
  (181, 'maldicao-para-duas', 'Maldição para duas', 'Victoria Mendes', 'sorteio', 'maldicao-para-duas.jpg', 'https://link.amazon/B0gn65k0m', 'sorteio'),
  (182, 'o-encontro-dos-sois', 'O encontro dos sóis', 'Carol Barra', 'sorteio', 'o-encontro-dos-sois.jpg', 'https://link.amazon/B0grpGQJn', 'sorteio'),
  (183, 'voce-e-minha-musa', 'Você é Minha Musa', 'Liliane Reis', 'sorteio', 'voce-e-minha-musa.jpg', 'https://link.amazon/B0gWivKUh', 'sorteio'),
  (184, 'completely', 'Completely', 'Golden Faery', 'sorteio', 'completely.jpg', 'https://link.amazon/B0gWiXRvu', 'sorteio'),
  (185, 'cool-for-the-summer', 'Cool for the summer', 'Dahlia Adler', 'sorteio', 'cool-for-the-summer.jpg', 'https://link.amazon/B0gxnOMTV', 'sorteio'),
  (186, 'minha-colega-de-quarto-e-uma-vampira', 'Minha Colega De Quarto É Uma Vampira', 'Ana França', 'sorteio', 'minha-colega-de-quarto-e-uma-vampira.jpg', 'https://link.amazon/B0hh45D70', 'sorteio'),
  (187, 'corrompidas', 'Corrompidas', 'Kimmcharlie', 'sorteio', 'corrompidas.jpg', 'https://link.amazon/B0hjLreVS', 'sorteio'),
  (188, 'dando-o-que-falar', 'Dando o que falar', 'Meryl Wilsner', 'sorteio', 'dando-o-que-falar.jpg', 'https://link.amazon/B0ho9SkvG', 'sorteio'),
  (189, 'entre-flocos-de-neve', 'Entre Flocos de Neve', 'Raquel Alves', 'sorteio', 'entre-flocos-de-neve.jpg', 'https://link.amazon/B0hUBBk0D', 'sorteio'),
  (190, 'tudo-que-ela-me-disse', 'Tudo que ela me disse', 'Bia Crespo', 'sorteio', 'tudo-que-ela-me-disse.jpg', 'https://link.amazon/B0iAX7Urx', 'sorteio'),
  (191, 'pegas-de-surpresa', 'Pegas de Surpresa', 'Adiba Jaigirdar', 'sorteio', 'pegas-de-surpresa.jpg', 'https://link.amazon/B0iFIzeFY', 'sorteio'),
  (192, 'recomenda-se-andar-acompanhada', 'Recomenda-se Andar Acompanhada', 'Tálita Heusi', 'sorteio', 'recomenda-se-andar-acompanhada.jpg', 'https://link.amazon/B0ipeMqlG', 'sorteio'),
  (193, 'as-tres-tarefas-de-cristina-ribeiro-de-castro', 'As três tarefas de Cristina Ribeiro de Castro', 'Laura Pohl', 'sorteio', 'as-tres-tarefas-de-cristina-ribeiro-de-castro.jpg', 'https://link.amazon/B0jlYgAca', 'sorteio'),
  (194, 'matalobos', 'Matalobos', 'Jules K. Florian', 'loja', 'matalobos.jpg', 'https://link.amazon/B00bzQtlv', 'loja'),
  (195, 'de-frente-para-o-amor', 'De Frente Para O Amor', 'Emely Luiza Curcio', 'loja', 'de-frente-para-o-amor.jpg', 'https://link.amazon/B00c7Eoww', 'loja'),
  (196, 'acordo-entre-amantes', 'Acordo Entre Amantes', 'Liliane Reis', 'loja', 'acordo-entre-amantes.jpg', 'https://link.amazon/B00dCDMUF', 'loja'),
  (197, 'cinco-minutos', 'Cinco Minutos', 'Ingrid Paranhos', 'loja', 'cinco-minutos.jpg', 'https://link.amazon/B00FdYk3l', 'loja'),
  (198, 'sob-os-tracos-da-paixao', 'Sob os traços da paixão', 'Zey Shelsea', 'loja', 'sob-os-tracos-da-paixao.jpg', 'https://link.amazon/B00vDcqlz', 'loja'),
  (199, 'o-preco-da-escuridao', 'O Preço da Escuridão', 'Danda Odeleci', 'loja', 'o-preco-da-escuridao.jpg', 'https://link.amazon/B015ngQ0P', 'loja'),
  (200, 'havana', 'Havana', 'Tessa Reis', 'loja', 'havana.jpg', 'https://link.amazon/B01ahoP1b', 'loja'),
  (201, 'imisturaveis', 'Imisturáveis', 'Kimmcharlie', 'loja', 'imisturaveis.jpg', 'https://link.amazon/B01na1VjJ', 'loja'),
  (202, 'amor-imprevisivel', 'Amor Imprevisível', 'Jess Lim', 'loja', 'amor-imprevisivel.jpg', 'https://link.amazon/B01OAdaCU', 'loja'),
  (203, 'entre-sombras-e-verdades', 'Entre sombras e verdades', 'Debora Carvalho', 'loja', 'entre-sombras-e-verdades.jpg', 'https://link.amazon/B01ObC7P4', 'loja'),
  (204, 'carmilla-fascinio-ebrio', 'Carmilla: Fascínio Ébrio', 'Mandy Vieira', 'loja', 'carmilla-fascinio-ebrio.jpg', 'https://link.amazon/B020aMl5w', 'loja'),
  (205, 'apenas-por-uma-noite', 'Apenas por uma noite', 'Zey Shelsea', 'loja', 'apenas-por-uma-noite.jpg', 'https://link.amazon/B021NAOMB', 'loja'),
  (206, 'a-unica-escolha-possivel', 'A única escolha possível', 'Carol Barra', 'loja', 'a-unica-escolha-possivel.jpg', 'https://link.amazon/B023vxFrU', 'loja'),
  (207, 'a-lenda-da-sereia-2', 'A lenda da sereia: 2', 'Clara Alves', 'loja', 'a-lenda-da-sereia-2.jpg', 'https://link.amazon/B02CpL7Bv', 'loja'),
  (208, 'de-admiradora-nada-secreta', 'De: Admiradora Nada Secreta', 'Tori Lopes', 'loja', 'de-admiradora-nada-secreta.jpg', 'https://link.amazon/B02GZHLpL', 'loja'),
  (209, 'asas-negras', 'Asas Negras', 'Debora Carvalho', 'loja', 'asas-negras.jpg', 'https://link.amazon/B02i0ZbUI', 'loja'),
  (210, 'como-sabotar-mia-espinosa', 'Como sabotar Mia Espinosa', 'Carol Cara, Liliane Reis', 'loja', 'como-sabotar-mia-espinosa.jpg', 'https://link.amazon/B02nNzKIP', 'loja'),
  (211, 'nem-todos-os-beijos-tem-gosto-de-inverno', 'Nem todos os beijos têm gosto de inverno', 'Yasmim Mahmud Kader', 'loja', 'nem-todos-os-beijos-tem-gosto-de-inverno.jpg', 'https://link.amazon/B02RohYpY', 'loja'),
  (212, 'um-acordo-de-dois-coracoes', 'Um acordo de dois coracões', 'Zey Shelsea, Yas Oliveira', 'loja', 'um-acordo-de-dois-coracoes.jpg', 'https://link.amazon/B02yh86Gm', 'loja'),
  (213, 'o-espelho-da-lua', 'O Espelho da Lua', 'Jia Monure', 'loja', 'o-espelho-da-lua.jpg', 'https://link.amazon/B032QtS6N', 'loja'),
  (214, 'a-garota-do-laco-vermelho', 'A Garota do Laço Vermelho', 'Isabella Pereira', 'loja', 'a-garota-do-laco-vermelho.jpg', 'https://link.amazon/B034tyx7f', 'loja'),
  (215, 'eufonia', 'Eufonia', 'Englantine', 'loja', 'eufonia.jpg', 'https://link.amazon/B037oBin9', 'loja'),
  (216, 'nuclea-a-queda-das-coroas-ancestrais', 'Nucléa: a queda das coroas ancestrais', 'Bia Freitas', 'loja', 'nuclea-a-queda-das-coroas-ancestrais.jpg', 'https://link.amazon/B038l03OJ', 'loja'),
  (217, 'isso-nao-e-um conto-de-fadas', 'Isso não é um conto de fadas', 'I.K. Prado', 'loja', 'isso-nao-e-um conto-de-fadas.jpg', 'https://link.amazon/B03AriqA6', 'loja'),
  (218, 'dramaticos', 'Dramáticos', 'Giu Nascimento, Jús Saraiva, Sol Alessandri,Thaís Berlanga, Luca Vasconcelos, Turí, Sol Braga', 'loja', 'dramaticos.jpg', 'https://link.amazon/B03Bef6Sc', 'loja'),
  (219, 'noturnas-e-natalinas', 'Noturnas e natalinas', 'Luisa Landre', 'loja', 'noturnas-e-natalinas.jpg', 'https://link.amazon/B03v3vEWz', 'loja'),
  (220, 'primavera-de-cinzas', 'Primavera de Cinzas', 'Larissa Ferrioli', 'loja', 'primavera-de-cinzas.jpg', 'https://link.amazon/B03VOw4cP', 'loja'),
  (221, 'fogo-cruzado', 'Fogo Cruzado', 'Carol Barra', 'loja', 'fogo-cruzado.jpg', 'https://link.amazon/B03XePKJL', 'loja'),
  (222, 'valentina', 'Valentina', 'Lis Selwyn', 'loja', 'valentina.jpg', 'https://link.amazon/B04aoeBaR', 'loja'),
  (223, 'mesa-pra-duas', 'Mesa Pra Duas', 'Alexia', 'loja', 'mesa-pra-duas.jpg', 'https://link.amazon/B04iNjhWt', 'loja'),
  (224, 'lie-for-you-destinos-entrelacados-livro-2', 'Lie For You (Destinos Entrelaçados Livro 2)', 'Swyanne Rodriguez', 'loja', 'lie-for-you-destinos-entrelacados-livro-2.jpg', 'https://link.amazon/B04jKQdeg', 'loja'),
  (225, 'o-melhor-erro-da-minha-vida', 'O melhor erro da minha vida', 'Zey Shelsea', 'loja', 'o-melhor-erro-da-minha-vida.jpg', 'https://link.amazon/B04LrAgkr', 'loja'),
  (226, 'o-triangulo', 'O Triângulo', 'Carol Rutz', 'loja', 'o-triangulo.jpg', 'https://link.amazon/B04MgFE1j', 'loja'),
  (227, 'nao-quero-ser-princesa', 'Não Quero Ser Princesa', 'Sarah Oliveira', 'loja', 'nao-quero-ser-princesa.jpg', 'https://link.amazon/B04mqyULW', 'loja'),
  (228, 'quando-sol-e-lua-se-apaixonam', 'Quando Sol e Lua se Apaixonam', 'Golden Faery', 'loja', 'quando-sol-e-lua-se-apaixonam.jpg', 'https://link.amazon/B04QPX3OI', 'loja'),
  (229, 'fios-de-sangue', 'Fios de sangue', 'Luisa Landre', 'loja', 'fios-de-sangue.jpg', 'https://link.amazon/B04TW4DQG', 'loja'),
  (230, 'o-sol-depois-da-chuva', 'O Sol Depois Da Chuva', 'Tori Lopes', 'loja', 'o-sol-depois-da-chuva.jpg', 'https://link.amazon/B04y5yzsr', 'loja'),
  (231, 'as-bruxas-de-lugar-nenhum-o-selo-livro-2', 'As Bruxas de Lugar Nenhum: O Selo - Livro 2', 'Denise Flaibam', 'loja', 'as-bruxas-de-lugar-nenhum-o-selo-livro-2.jpg', 'https://link.amazon/B05q7jUlr', 'loja'),
  (232, 'eu-me-rendo-e-me-entrego-ate-depois-do-fim', 'Eu Me Rendo E Me Entrego até depois do fim', 'Márcia Camargo', 'loja', 'eu-me-rendo-e-me-entrego-ate-depois-do-fim.jpg', 'https://link.amazon/B05UIeqLR', 'loja'),
  (233, 'quarto-119', 'Quarto 119', 'Raquel Alves', 'loja', 'quarto-119.jpg', 'https://link.amazon/B061nQJ9R', 'loja'),
  (234, 'mil-coracoes-por-um-reino', 'Mil Corações por um Reino', 'Yasmim Mahmud Kader', 'loja', 'mil-coracoes-por-um-reino.jpg', 'https://link.amazon/B06cnrdix', 'loja'),
  (235, 'uma-mulher-pra-chamar-de-minha', 'Uma mulher pra chamar de minha', 'Thais Rodrigues', 'loja', 'uma-mulher-pra-chamar-de-minha.jpg', 'https://link.amazon/B06CSQ3DH', 'loja'),
  (236, 'o-toque-letal-do-corvo', 'O Toque Letal do Corvo', 'Mariana Rosa', 'loja', 'o-toque-letal-do-corvo.jpg', 'https://link.amazon/B06F7RvL7', 'loja'),
  (237, 'sou-tudo-o-que-voce-nao-precisa', 'Sou tudo o que você (não) precisa', 'V.S. Vilela', 'loja', 'sou-tudo-o-que-voce-nao-precisa.jpg', 'https://link.amazon/B06JTmSgt', 'loja'),
  (238, 'heartstaker', 'Heartstaker', 'Victoria Mendes', 'loja', 'heartstaker.jpg', 'https://link.amazon/B06lMtSYG', 'loja'),
  (239, '25-de-outubro-o-preco-de-um-unico-dia', '25 de Outubro: O preço de um único dia', 'Emely Luiza Curcio', 'loja', '25-de-outubro-o-preco-de-um-unico-dia.jpg', 'https://link.amazon/B06MNs2Hm', 'loja'),
  (240, 'inimigas-secretas', 'Inimigas Secretas', 'Ju Mesquita', 'loja', 'inimigas-secretas.jpg', 'https://link.amazon/B06NNk8we', 'loja'),
  (241, '24-horas-para-nao-se-apaixonar', '24 horas para não se apaixonar', 'Helena Nolasco, Milly Ricardo', 'loja', '24-horas-para-nao-se-apaixonar.jpg', 'https://link.amazon/B07BgIoLU', 'loja'),
  (242, 'stupid-wife-lembre-se-de-nos', 'Stupid Wife: Lembre-se de Nós', 'Sodré', 'loja', 'stupid-wife-lembre-se-de-nos.jpg', 'https://link.amazon/B07Gmppl3', 'loja'),
  (243, 'aguas-de-marco-vol-2', 'Águas de Março, vol.2', 'Gisele Cerqueira, Hannah Kaiser', 'loja', 'aguas-de-marco-vol-2.jpg', 'https://link.amazon/B08EA96yg', 'loja'),
  (244, 'um-milhao-de-maneiras-de-cacar-voce', 'Um milhão de maneiras de caçar você', 'Denise Flaibam', 'loja', 'um-milhao-de-maneiras-de-cacar-voce.jpg', 'https://link.amazon/B08hRGhaT', 'loja'),
  (245, 'pausa-para-respirar', 'Pausa para Respirar', 'Liliane Reis', 'loja', 'pausa-para-respirar.jpg', 'https://link.amazon/B08spB9AG', 'loja'),
  (246, 'alegoria', 'Alegoria', 'Danda Odeleci', 'loja', 'alegoria.jpg', 'https://link.amazon/B08V3TV8c', 'loja'),
  (247, 'procura-se', 'Procura-se', 'Tattah Nascimento', 'loja', 'procura-se.jpg', 'https://link.amazon/B08WCN5A8', 'loja'),
  (248, 'o-destino-de-tilda', 'O Destino de Tilda', 'Denise Flaibam', 'loja', 'o-destino-de-tilda.jpg', 'https://link.amazon/B09bHdwkm', 'loja'),
  (249, 'como-seduzir-a-capita', 'Como Seduzir a Capitã', 'Sarah Oliveira', 'loja', 'como-seduzir-a-capita.jpg', 'https://link.amazon/B09GDoPwm', 'loja'),
  (250, 'o-destino-da-sereia-3', 'O destino da sereia: 3', 'Clara Alves', 'loja', 'o-destino-da-sereia-3.jpg', 'https://link.amazon/B09gUXCWk', 'loja'),
  (251, 'caso-perdido', 'Caso Perdido', 'Victoria Moon', 'loja', 'caso-perdido.jpg', 'https://link.amazon/B09HhiHdh', 'loja'),
  (252, 'dona-do-meu-pecado-recomeco', 'Dona do meu pecado - Recomeço', 'Fernanda Moser', 'loja', 'dona-do-meu-pecado-recomeco.jpg', 'https://link.amazon/B0a1btptN', 'loja'),
  (253, 'boas-maneiras', 'Boas Maneiras', 'Englantine', 'loja', 'boas-maneiras.jpg', 'https://link.amazon/B0ad7C58n', 'loja'),
  (254, 'quebrando-as-nossas-regras', 'Quebrando as nossas regras', 'Lari Alcantara', 'loja', 'quebrando-as-nossas-regras.jpg', 'https://link.amazon/B0aDxszBF', 'loja'),
  (255, 'entre-sussurros', 'Entre Sussurros', 'Brenda Borges', 'loja', 'entre-sussurros.jpg', 'https://link.amazon/B0ahda1UC', 'loja'),
  (256, 'a-farsa-de-laura-beatriz', 'A Farsa de Laura Beatriz', 'Victoria Moon', 'loja', 'a-farsa-de-laura-beatriz.jpg', 'https://link.amazon/B0akoiJXn', 'loja'),
  (257, 'sobre-namoradas-e-lobos', 'Sobre Namoradas e Lobos', 'Marina Feijóo', 'loja', 'sobre-namoradas-e-lobos.jpg', 'https://link.amazon/B0aMoID7l', 'loja'),
  (258, 'salik-amor-ruina', 'Salik: Amor & Ruína', 'Bia R.D. Ramos', 'loja', 'salik-amor-ruina.jpg', 'https://link.amazon/B0aqpV1y5', 'loja'),
  (259, 'a-profecia-da-sereia-1', 'A profecia da sereia: 1', 'Clara Alves', 'loja', 'a-profecia-da-sereia-1.jpg', 'https://link.amazon/B0aV8AOtB', 'loja'),
  (260, 'atlas', 'ATLAS', 'Carol Cara', 'loja', 'atlas.jpg', 'https://link.amazon/B0b1HsQXl', 'loja'),
  (261, 'eco-de-nos', 'Eco de nós', 'Evyn Mota', 'loja', 'eco-de-nos.jpg', 'https://link.amazon/B0b6VwHEC', 'loja'),
  (262, 'o-corpo-na-cozinha', 'O Corpo na Cozinha', 'Vanessa Freitas', 'loja', 'o-corpo-na-cozinha.jpg', 'https://link.amazon/B0b8gdFpQ', 'loja'),
  (263, 'traicao-segredos-e-mentiras', 'Traição, Segredos e Mentiras', 'Emely Luiza Curcio', 'loja', 'traicao-segredos-e-mentiras.jpg', 'https://link.amazon/B0ba3k5x0', 'loja'),
  (264, 'a-pior-das-boas-ideias', 'A pior das boas ideias', 'V.S. Vilela', 'loja', 'a-pior-das-boas-ideias.jpg', 'https://link.amazon/B0bCeSQcE', 'loja'),
  (265, 'fantasma-da-meia-noite', 'Fantasma Da Meia-Noite', 'Tori Lopes', 'loja', 'fantasma-da-meia-noite.jpg', 'https://link.amazon/B0bgMEs7M', 'loja'),
  (266, 'venenosas', 'Venenosas', 'Ana França', 'loja', 'venenosas.jpg', 'https://link.amazon/B0biCeowH', 'loja'),
  (267, 'polaris', 'Polaris', 'Giu Nascimento', 'loja', 'polaris.jpg', 'https://link.amazon/B0bpbUwjy', 'loja'),
  (268, 'odio-carmesim', 'Ódio Carmesim', 'Swyanne Rodriguez', 'loja', 'odio-carmesim.jpg', 'https://link.amazon/B0bpdZxeB', 'loja'),
  (269, 'first-class', 'First Class', 'Tessa Reis', 'loja', 'first-class.jpg', 'https://link.amazon/B0bPECHse', 'loja'),
  (270, 'a-princesa-que-eu-sempre-quis', 'A princesa que eu sempre quis', 'Vanessa Freitas', 'loja', 'a-princesa-que-eu-sempre-quis.jpg', 'https://link.amazon/B0br3jJUY', 'loja'),
  (271, 'sementes-divinas', 'Sementes Divinas', 'Debora Carvalho', 'loja', 'sementes-divinas.jpg', 'https://link.amazon/B0bxyZSfl', 'loja'),
  (272, 'fora-de-campo', 'Fora de campo', 'D. Barreto', 'loja', 'fora-de-campo.jpg', 'https://link.amazon/B0bZfHNl3', 'loja'),
  (273, 'sob-nova-direcao', 'Sob Nova Direção', 'Englantine', 'loja', 'sob-nova-direcao.jpg', 'https://link.amazon/B0ciNIDG2', 'loja'),
  (274, 'a-guarda-costas-parte-1', 'A Guarda-Costas: Parte I', 'G.B. Baldassari', 'loja', 'a-guarda-costas-parte-1.jpg', 'https://link.amazon/B0cITOsWM', 'loja'),
  (275, 'as-regras-do-jogo', 'As regras do jogo', 'Arquelana', 'loja', 'as-regras-do-jogo.jpg', 'https://link.amazon/B0cm7egoh', 'loja'),
  (276, 'a-ultima-luz-do-verao', 'A Última Luz do Verão', 'Gina Milbradt', 'loja', 'a-ultima-luz-do-verao.jpg', 'https://link.amazon/B0cpDl47c', 'loja'),
  (277, 'crimes-do-amor', 'Crimes do Amor', 'Tattah Nascimento', 'loja', 'crimes-do-amor.jpg', 'https://link.amazon/B0d6taq9X', 'loja'),
  (278, 'amor-improvisado', 'Amor Improvisado', 'Jess Lim', 'loja', 'amor-improvisado.jpg', 'https://link.amazon/B0dEAIkd4', 'loja'),
  (279, 'imperfectely', 'Imperfectely', 'Golden Faery', 'loja', 'imperfectely.jpg', 'https://link.amazon/B0dI2yOn5', 'loja'),
  (280, 'como-amar-uma-rainha', 'Como Amar uma Rainha', 'Milly Ricardo', 'loja', 'como-amar-uma-rainha.jpg', 'https://link.amazon/B0dT3w73K', 'loja'),
  (281, 'garotas-boas-tambem-queimam', 'Garotas boas também queimam', 'Victoria Mendes', 'loja', 'garotas-boas-tambem-queimam.jpg', 'https://link.amazon/B0eAfDyg8', 'loja'),
  (282, 'ponto-sem-no', 'Ponto sem nó', 'Ingrid Paranhos', 'loja', 'ponto-sem-no.jpg', 'https://link.amazon/B0efMuvqV', 'loja'),
  (283, 'os-que-esperam-nas-sombras', 'Os Que Esperam Nas Sombras', 'Jules K. Florian', 'loja', 'os-que-esperam-nas-sombras.jpg', 'https://link.amazon/B0ejV7GKC', 'loja'),
  (284, 'pink-lemonade', 'Pink Lemonade', 'G.B. Baldassari', 'loja', 'pink-lemonade.jpg', 'https://link.amazon/B0jlmOBSj', 'loja'),
  (285, 'um-noivado-de-farsa-para-sofia', 'Um noivado de farsa para Sofia', 'Helena Nolasco', 'loja', 'um-noivado-de-farsa-para-sofia.jpg', 'https://link.amazon/B0emezUyB', 'loja'),
  (286, 'eu-so-quero-ser-sua', 'Eu só quero ser sua', 'Liliane Reis', 'loja', 'eu-so-quero-ser-sua.jpg', 'https://link.amazon/B0eNmH77E', 'loja'),
  (287, 'as-paginas-de-um-desejo-proibido', 'As Páginas de um Desejo Proibido', 'Mariana Rosa', 'loja', 'as-paginas-de-um-desejo-proibido.jpg', 'https://link.amazon/B0jaKgck6', 'loja'),
  (288, 'todas-as-verdades-que-eu-nao-te-disse', 'Todas as verdades que eu não te disse', 'D. Barreto', 'loja', 'todas-as-verdades-que-eu-nao-te-disse.jpg', 'https://link.amazon/B0eSZovXB', 'loja'),
  (289, 'fique-comigo-para-o-jantar', 'Fique comigo para o jantar', 'I.K. Prado', 'loja', 'fique-comigo-para-o-jantar.jpg', 'https://link.amazon/B0euJmqZD', 'loja'),
  (290, 'entre-beijos-e-flechas', 'Entre beijos e flechas', 'Vanessa Freitas', 'loja', 'entre-beijos-e-flechas.jpg', 'https://link.amazon/B0ey353aX', 'loja'),
  (291, 'a-garota-que-eu-nunca-esqueci', 'A garota que eu nunca esqueci', 'Carol Cara, Liliane Reis', 'loja', 'a-garota-que-eu-nunca-esqueci.jpg', 'https://link.amazon/B0ezW5Ai5', 'loja'),
  (292, 'antes-do-sim', 'Antes do sim', 'Nicole Oliveira', 'loja', 'antes-do-sim.jpg', 'https://link.amazon/B0f0DQMnx', 'loja'),
  (293, 'garotas-como-eu', 'Garotas como eu', 'Lis Selwyn', 'loja', 'garotas-como-eu.jpg', 'https://link.amazon/B0f0Zkw7K', 'loja'),
  (294, 'eu-me-rendo-e-me-entrego', 'Eu Me Rendo E Me Entrego', 'Márcia Camargo', 'loja', 'eu-me-rendo-e-me-entrego.jpg', 'https://link.amazon/B0fE7NPfS', 'loja'),
  (295, 'estilazo', 'Estilazo', 'Tessa Reis', 'loja', 'estilazo.jpg', 'https://link.amazon/B0fgacHlK', 'loja'),
  (296, 'todas-as-nossas-primeiras-vezes', 'Todas as Nossas Primeiras Vezes', 'Bia R.D. Ramos', 'loja', 'todas-as-nossas-primeiras-vezes.jpg', 'https://link.amazon/B0fKHlcsf', 'loja'),
  (297, 'a-conquistadora-de-estrelas', 'A conquistadora de estrelas', 'Natalia Avila', 'loja', 'a-conquistadora-de-estrelas.jpg', 'https://link.amazon/B0gBWZ3qN', 'loja'),
  (298, 'nao-foi-o-destino', 'Não foi o destino', 'Graziela Santos', 'loja', 'nao-foi-o-destino.jpg', 'https://link.amazon/B0gCU1NdH', 'loja'),
  (299, 'meia-noite-no-parque', 'Meia-noite no Parque', 'Helena Nolasco', 'loja', 'meia-noite-no-parque.jpg', 'https://link.amazon/B0glHEbf7', 'loja'),
  (300, 'ristretto', 'Ristretto', 'Tessa Reis', 'loja', 'ristretto.jpg', 'https://link.amazon/B0grKaSql', 'loja'),
  (301, 'as-novas-romanticas', 'As Novas Românticas', 'Luisa Landre', 'loja', 'as-novas-romanticas.jpg', 'https://link.amazon/B0gRkOfoz', 'loja'),
  (302, 'a-ordem-a-eleita', 'A Ordem: A Eleita', 'Tattah Nascimento', 'loja', 'a-ordem-a-eleita.jpg', 'https://link.amazon/B0gSsfX1R', 'loja'),
  (303, 'tons-do-amor', 'Tons do Amor', 'Lari Alcantara', 'loja', 'tons-do-amor.jpg', 'https://link.amazon/B0gyoaWm4', 'loja'),
  (304, 'desarmonia', 'Desarmonia', 'Raquel Alves', 'loja', 'desarmonia.jpg', 'https://link.amazon/B0gYRU3Ie', 'loja'),
  (305, 'um-fake-dating-quase-perfeito', 'Um fake dating (quase) perfeito', 'Thais Rodrigues', 'loja', 'um-fake-dating-quase-perfeito.jpg', 'https://link.amazon/B0habx9xJ', 'loja'),
  (306, '24h-para-correr', '24h Para Correr', 'Marina Dutra', 'loja', '24h-para-correr.jpg', 'https://link.amazon/B0hDlnLp7', 'loja'),
  (307, 'pior-pesadelo-de-um-homem', 'Pior Pesadelo de um Homem', 'Marina Feijóo', 'loja', 'pior-pesadelo-de-um-homem.jpg', 'https://link.amazon/B0hTdiVYa', 'loja'),
  (308, 'tudo-o-que-nao-toleramos', 'Tudo o que (não) toleramos', 'Helena Nolasco', 'loja', 'tudo-o-que-nao-toleramos.jpg', 'https://link.amazon/B0hUZbTZq', 'loja'),
  (309, 'as-nossas-nuvens-de-algodao-doce', 'As Nossas Nuvens de Algodão Doce', 'Ana França', 'loja', 'as-nossas-nuvens-de-algodao-doce.jpg', 'https://link.amazon/B0hWWoyxR', 'loja'),
  (310, 'amparia', 'Ampária', 'Júlia Raimann', 'loja', 'amparia.jpg', 'https://link.amazon/B0hXSLAeM', 'loja'),
  (311, 'a-inquisicao-escarlate', 'A Inquisição Escarlate', 'Thaís Boito', 'loja', 'a-inquisicao-escarlate.jpg', 'https://link.amazon/B0i3ARiB6', 'loja'),
  (312, 'intemperies-de-verao', 'Intempéries de Verão', 'Ana França', 'loja', 'intemperies-de-verao.jpg', 'https://link.amazon/B0i8z4z0B', 'loja'),
  (313, 'living-in-you-destinos-entrelacados-livro-3', 'Living In You (Destinos Entrelaçados Livro 3)', 'Swyanne Rodriguez', 'loja', 'living-in-you-destinos-entrelacados-livro-3.jpg', 'https://link.amazon/B0i9nVSwa', 'loja'),
  (314, 'o-contrato', 'O Contrato', 'Tessa Reis', 'loja', 'o-contrato.jpg', 'https://link.amazon/B0idkR7Qs', 'loja'),
  (315, 'joanesburgo', 'Joanesburgo', 'Victoria Mendes', 'loja', 'joanesburgo.jpg', 'https://link.amazon/B0ifH9HS6', 'loja'),
  (316, 'o-cafe-pode-ser-a-resposta', 'O café pode ser a resposta', 'Golden Faery', 'loja', 'o-cafe-pode-ser-a-resposta.jpg', 'https://link.amazon/B0illxJCE', 'loja'),
  (317, 'tudo-se-tornou-ela', 'Tudo se tornou ela', 'Raquel Alves', 'loja', 'tudo-se-tornou-ela.jpg', 'https://link.amazon/B0iN6aBcn', 'loja'),
  (318, 'a-princesa-e-o-cappuccino', 'A Princesa e o Cappuccino', 'G.B. Baldassari', 'loja', 'a-princesa-e-o-cappuccino.jpg', 'https://link.amazon/B0j5M76xK', 'loja'),
  (319, 'a-escolhida-da-deusa', 'A Escolhida da Deusa', 'Mariana Rosa', 'loja', 'a-escolhida-da-deusa.jpg', 'https://link.amazon/B0jaIxOHK', 'loja'),
  (320, 'de-repente-casadas-ilustracao', 'De Repente Namoradas', 'G.B. Baldassari', 'exclusiva', 'de-repente-casadas-ilustracao.jpg', 'https://link.amazon/B00yWsZ55', 'exclusiva'),
  (321, 'polaris-ilustracao', 'Polaris (ou ela não é daqui)', 'Giu Nascimento', 'exclusiva', 'polaris-ilustracao.jpg', 'https://link.amazon/B02LbppPN', 'exclusiva'),
  (322, 'todas-as-verdades-que-eu-nao-te-disse-ilustracao', 'Todas as verdades que eu não te disse', 'D. Barreto', 'exclusiva', 'todas-as-verdades-que-eu-nao-te-disse-ilustracao.jpg', 'https://link.amazon/B033rHRRk', 'exclusiva'),
  (323, 'o-encontro-dos-sois-1-ilustracao', 'O encontro dos sóis', 'Carol Barra', 'exclusiva', 'o-encontro-dos-sois-1-ilustracao.jpg', 'https://link.amazon/B03QSC7A3', 'exclusiva'),
  (324, 'antes-do-sim-ilustracao', 'Antes do Sim', 'Nicole Oliveira', 'exclusiva', 'antes-do-sim-ilustracao.jpg', 'https://link.amazon/B03WvvuYj', 'exclusiva'),
  (325, 'living-in-you-ilustracao', 'Living In You (Destinos Entrelaçados Livro 3)', 'Swyanne Rodriguez', 'exclusiva', 'living-in-you-ilustracao.jpg', 'https://link.amazon/B04Y5T3dp', 'exclusiva'),
  (326, 'valentina-ilustracao', 'Valentina', 'Lis Selwyn', 'exclusiva', 'valentina-ilustracao.jpg', 'https://link.amazon/B059HSb7R', 'exclusiva'),
  (327, 'segundo-cliche-ilustracao', 'Segundo Clichê', 'Line Cunha', 'exclusiva', 'segundo-cliche-ilustracao.jpg', 'https://link.amazon/B0fpykQup', 'exclusiva'),
  (328, 'feras-em-campo-ilustracao', 'Feras em campo', 'Luisa Landre', 'exclusiva', 'feras-em-campo-ilustracao.jpg', 'https://link.amazon/B05bC3xnx', 'exclusiva'),
  (329, 'sou-tao-o-que-voce-nao-precisa-ilustracao', 'Sou tudo o que você (não) precisa', 'V.S. Vilela', 'exclusiva', 'sou-tao-o-que-voce-nao-precisa-ilustracao.jpg', 'https://link.amazon/B065GZUKC', 'exclusiva'),
  (330, 'amor-imprevisivel-ilustracao', 'Amor Imprevisível', 'Jess Lim', 'exclusiva', 'amor-imprevisivel-ilustracao.jpg', 'https://link.amazon/B067XVJtk', 'exclusiva'),
  (331, '24h-para-correr-ilustracao-1', '24h Para Correr', 'Marina Dutra', 'exclusiva', '24h-para-correr-ilustracao-1.jpg', 'https://link.amazon/B09LP2VIp', 'exclusiva'),
  (332, 'desarmonia-ilustracao', 'Desarmonia', 'Raquel Alves', 'exclusiva', 'desarmonia-ilustracao.jpg', 'https://link.amazon/B06FsCyNJ', 'exclusiva'),
  (333, 'ultimo-romance-ilustracao', 'Último Romance', 'Thais Rodrigues', 'exclusiva', 'ultimo-romance-ilustracao.jpg', 'https://link.amazon/B0ggERHkt', 'exclusiva'),
  (334, 'romance-real-ilustracao', 'Romance real', 'Clara Alves', 'exclusiva', 'romance-real-ilustracao.jpg', 'https://link.amazon/B06KzJZ3U', 'exclusiva'),
  (335, 'traicao-segredos-e-mentiras-ilustracao', 'Traição, Segredos e Mentiras', 'Emely Luiza Curcio', 'exclusiva', 'traicao-segredos-e-mentiras-ilustracao.jpg', 'https://link.amazon/B079j6gRF', 'exclusiva'),
  (336, 'pink-lemonade-ilustracao', 'Pink Lemonade', 'G.B. Baldassari', 'exclusiva', 'pink-lemonade-ilustracao.jpg', 'https://link.amazon/B07B0KfaK', 'exclusiva'),
  (337, 'quarto-119-ilustracao', 'Quarto 119', 'Raquel Alves', 'exclusiva', 'quarto-119-ilustracao.jpg', 'https://link.amazon/B07wtbo3K', 'exclusiva'),
  (338, 'amor-fati-ilustracao', 'Amor Fati', 'G.B. Baldassari', 'exclusiva', 'amor-fati-ilustracao.jpg', 'https://link.amazon/B01nxolvw', 'exclusiva'),
  (339, 'como-nao-se-apaixonar-ilustracao', 'Como (não) se apaixonar', 'D. Barreto', 'exclusiva', 'como-nao-se-apaixonar-ilustracao.jpg', 'https://link.amazon/B08EySi9l', 'exclusiva'),
  (340, 'cerejas-do-inferno-ilustracao', 'Cerejas do Inferno', 'Thaís Boito', 'exclusiva', 'cerejas-do-inferno-ilustracao.jpg', 'https://link.amazon/B09cPwtrj', 'exclusiva'),
  (341, 'a-conquistadora-de-estrelas-ilustracao-1', 'A conquistadora de estrelas', 'Natalia Avila', 'exclusiva', 'a-conquistadora-de-estrelas-ilustracao-1.jpg', 'https://link.amazon/B09d1H5Yw', 'exclusiva'),
  (342, 'reconstrucao-ilustracao', 'Reconstrução', 'Andremis', 'exclusiva', 'reconstrucao-ilustracao.jpg', 'https://link.amazon/B09iXvqKn', 'exclusiva'),
  (343, 'fogo-cruzado-ilustacao', 'Fogo Cruzado', 'Carol Barra', 'exclusiva', 'fogo-cruzado-ilustacao.jpg', 'https://link.amazon/B09JcmWWq', 'exclusiva'),
  (344, 'as-novas-romanticas-ilustracao', 'As Novas Românticas', 'Luisa Landre', 'exclusiva', 'as-novas-romanticas-ilustracao.jpg', 'https://link.amazon/B05Ywfldr', 'exclusiva'),
  (345, '24h-para-correr-ilustracao-2', '24h Para Correr', 'Marina Dutra', 'exclusiva', '24h-para-correr-ilustracao-2.jpg', 'https://link.amazon/B09LP2VIp', 'exclusiva'),
  (346, '25-de-outubro-ilustracao', '25 de Outubro: O preço de um único dia', 'Emely Luiza Curcio', 'exclusiva', '25-de-outubro-ilustracao.jpg', 'https://link.amazon/B0aUB5g8m', 'exclusiva'),
  (347, 'uma-mulher-pra-chamar-de-minha-ilustracao', 'Uma mulher pra chamar de minha', 'Thais Rodrigues', 'exclusiva', 'uma-mulher-pra-chamar-de-minha-ilustracao.jpg', 'https://link.amazon/B0bGNchjo', 'exclusiva'),
  (348, 'lost-on-you-ilustracao', 'Lost On You (Destinos Entrelaçados Livro 1)', 'Swyanne Rodriguez', 'exclusiva', 'lost-on-you-ilustracao.jpg', 'https://link.amazon/B0c1haJRt', 'exclusiva'),
  (349, 'conectadas-ilustracao', 'Conectadas', 'Clara Alves', 'exclusiva', 'conectadas-ilustracao.jpg', 'https://link.amazon/B0cLLfn8I', 'exclusiva'),
  (350, 'a-pior-das-boas-ideias-ilustracao', 'A pior das boas ideias', 'V.S. Vilela', 'exclusiva', 'a-pior-das-boas-ideias-ilustracao.jpg', 'https://link.amazon/B0cV92ih3', 'exclusiva'),
  (351, 'nao-foi-o-destino-ilustracao', 'Não foi o destino', 'Graziela Santos', 'exclusiva', 'nao-foi-o-destino-ilustracao.jpg', 'https://link.amazon/B0cZO4346', 'exclusiva'),
  (352, 'fora-de-campo-ilustracao', 'Fora de campo', 'D. Barreto', 'exclusiva', 'fora-de-campo-ilustracao.jpg', 'https://link.amazon/B0dFdKEsf', 'exclusiva'),
  (353, 'proibido-se-apaixonar-de-novo-ilustracao', 'Proibido se apaixonar de novo', 'V.S. Vilela', 'exclusiva', 'proibido-se-apaixonar-de-novo-ilustracao.jpg', 'https://link.amazon/B0dQeLXYz', 'exclusiva'),
  (354, 'galaxia-desconhecida-ilustracao', 'Galáxia desconhecida', 'Raquel Alves', 'exclusiva', 'galaxia-desconhecida-ilustracao.jpg', 'https://link.amazon/B0erWN7xB', 'exclusiva'),
  (355, 'o-encontro-dos-sois-2-ilustracao', 'O encontro dos sóis', 'Carol Barra', 'exclusiva', 'o-encontro-dos-sois-2-ilustracao.jpg', 'https://link.amazon/B03QSC7A3', 'exclusiva'),
  (356, 'terceiro-croqui-ilustracao', 'Terceiro Croqui', 'Line Cunha', 'exclusiva', 'terceiro-croqui-ilustracao.jpg', 'https://link.amazon/B0gSXsw14', 'exclusiva'),
  (357, 'crimes-do-amor-ilustracao', 'Crimes do Amor', 'Táttah Nascimento', 'exclusiva', 'crimes-do-amor-ilustracao.jpg', 'https://link.amazon/B0gZLEgl8', 'exclusiva'),
  (358, 'um-fake-dating-quase-perfeito-ilustracao', 'Um fake dating (quase) perfeito', 'Thais Rodrigues', 'exclusiva', 'um-fake-dating-quase-perfeito-ilustracao.jpg', 'https://link.amazon/B0hMtCTyn', 'exclusiva'),
  (359, 'garotas-como-eu-ilustracao', 'Garotas como eu', 'Lis Selwyn', 'exclusiva', 'garotas-como-eu-ilustracao.jpg', 'https://link.amazon/B0hzm9p8I', 'exclusiva'),
  (360, 'operacao-conves-ilustracao', 'Operação Convés', 'Line Cunha', 'exclusiva', 'operacao-conves-ilustracao.jpg', 'https://link.amazon/B080YKbsw', 'exclusiva')
on conflict (number) do update set
  slug = excluded.slug,
  name = excluded.name,
  author = excluded.author,
  type = excluded.type,
  cover_url = excluded.cover_url,
  amazon_url = excluded.amazon_url,
  category = excluded.category;

do $$
begin
  if (select count(*) from public.stickers where number between 1 and 360) <> 360 then
    raise exception 'A tabela public.stickers nao ficou com as 360 figurinhas esperadas.';
  end if;
end $$;
