-- Purchase ledger for the V2 shop.
-- This moves the payment/order history out of the browser and into Supabase.
-- Every order, payment, pack and sticker generated by a purchase receives its own stable id.

create extension if not exists "uuid-ossp";

alter table public.stickers
  add column if not exists ilustrator text;

create table if not exists public.shop_products (
  id text primary key,
  name text not null,
  description text,
  product_type text not null check (product_type in ('pack', 'combo', 'single_random', 'exclusive')),
  sticker_number integer references public.stickers(number) on delete restrict,
  pack_count integer not null default 0 check (pack_count >= 0),
  stickers_per_pack integer not null default 0 check (stickers_per_pack >= 0),
  price_cents integer not null check (price_cents >= 0),
  currency text not null default 'BRL',
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_products_exclusive_requires_sticker check (
    (product_type = 'exclusive' and sticker_number is not null)
    or (product_type <> 'exclusive' and sticker_number is null)
  )
);

create table if not exists public.purchase_orders (
  id uuid primary key default uuid_generate_v4(),
  order_code text not null unique default ('CDC-' || upper(substr(replace(uuid_generate_v4()::text, '-', ''), 1, 10))),
  user_id uuid not null references public.profiles(id) on delete restrict,
  status text not null default 'created' check (
    status in ('created', 'pending_payment', 'approved', 'partially_opened', 'completed', 'cancelled', 'expired', 'refunded', 'chargeback')
  ),
  payment_provider text not null default 'mercadopago',
  external_reference text not null unique default uuid_generate_v4()::text,
  checkout_url text,
  init_point text,
  sandbox_init_point text,
  total_cents integer not null default 0 check (total_cents >= 0),
  currency text not null default 'BRL',
  items_snapshot jsonb not null default '[]'::jsonb,
  payment_snapshot jsonb,
  created_at timestamptz not null default now(),
  payment_pending_at timestamptz,
  payment_approved_at timestamptz,
  cancelled_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists purchase_orders_user_created_idx
  on public.purchase_orders(user_id, created_at desc);

create index if not exists purchase_orders_status_idx
  on public.purchase_orders(status);

create table if not exists public.purchase_order_items (
  id uuid primary key default uuid_generate_v4(),
  order_id uuid not null references public.purchase_orders(id) on delete cascade,
  product_id text references public.shop_products(id) on delete restrict,
  product_name text not null,
  product_type text not null check (product_type in ('pack', 'combo', 'single_random', 'exclusive')),
  sticker_number integer references public.stickers(number) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  total_price_cents integer not null check (total_price_cents >= 0),
  pack_count integer not null default 0 check (pack_count >= 0),
  stickers_per_pack integer not null default 0 check (stickers_per_pack >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists purchase_order_items_order_idx
  on public.purchase_order_items(order_id);

create table if not exists public.purchase_payments (
  id uuid primary key default uuid_generate_v4(),
  order_id uuid not null references public.purchase_orders(id) on delete cascade,
  provider text not null default 'mercadopago',
  provider_payment_id text,
  provider_preference_id text,
  provider_merchant_order_id text,
  status text not null default 'created',
  status_detail text,
  payment_method_id text,
  payment_type_id text,
  transaction_amount_cents integer,
  net_received_amount_cents integer,
  currency text not null default 'BRL',
  payer_email text,
  payer_id text,
  webhook_event_id text,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(provider, provider_payment_id),
  unique(provider, webhook_event_id)
);

create index if not exists purchase_payments_order_idx
  on public.purchase_payments(order_id, created_at desc);

create table if not exists public.purchase_packs (
  id uuid primary key default uuid_generate_v4(),
  order_id uuid not null references public.purchase_orders(id) on delete cascade,
  order_item_id uuid references public.purchase_order_items(id) on delete set null,
  user_id uuid not null references public.profiles(id) on delete restrict,
  pack_number integer not null,
  title text not null default '1x Pacote',
  pack_type text not null default 'pack' check (pack_type in ('pack', 'single_random', 'exclusive')),
  status text not null default 'pending' check (status in ('pending', 'opening', 'opened', 'cancelled', 'refunded')),
  generated_at timestamptz not null default now(),
  opened_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id, pack_number)
);

create index if not exists purchase_packs_user_status_idx
  on public.purchase_packs(user_id, status, created_at desc);

create table if not exists public.purchase_pack_stickers (
  id uuid primary key default uuid_generate_v4(),
  pack_id uuid not null references public.purchase_packs(id) on delete cascade,
  order_id uuid not null references public.purchase_orders(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete restrict,
  sticker_number integer not null references public.stickers(number) on delete restrict,
  position integer not null check (position > 0),
  was_new_at_generation boolean,
  was_repeat_at_generation boolean,
  is_rare boolean not null default false,
  source text not null default 'shop',
  applied_to_inventory_at timestamptz,
  created_at timestamptz not null default now(),
  unique(pack_id, position)
);

create index if not exists purchase_pack_stickers_pack_idx
  on public.purchase_pack_stickers(pack_id, position);

create index if not exists purchase_pack_stickers_user_created_idx
  on public.purchase_pack_stickers(user_id, created_at desc);

create table if not exists public.purchase_events (
  id uuid primary key default uuid_generate_v4(),
  order_id uuid references public.purchase_orders(id) on delete cascade,
  payment_id uuid references public.purchase_payments(id) on delete set null,
  user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists purchase_events_order_created_idx
  on public.purchase_events(order_id, created_at desc);

alter table public.shop_products enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;
alter table public.purchase_payments enable row level security;
alter table public.purchase_packs enable row level security;
alter table public.purchase_pack_stickers enable row level security;
alter table public.purchase_events enable row level security;

drop policy if exists "shop_products_public_read_active" on public.shop_products;
create policy "shop_products_public_read_active"
  on public.shop_products for select
  to anon, authenticated
  using (active = true);

drop policy if exists "purchase_orders_read_own" on public.purchase_orders;
create policy "purchase_orders_read_own"
  on public.purchase_orders for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "purchase_order_items_read_own" on public.purchase_order_items;
create policy "purchase_order_items_read_own"
  on public.purchase_order_items for select
  to authenticated
  using (
    exists (
      select 1 from public.purchase_orders po
      where po.id = purchase_order_items.order_id
        and po.user_id = auth.uid()
    )
  );

drop policy if exists "purchase_payments_read_own" on public.purchase_payments;

drop policy if exists "purchase_packs_read_own" on public.purchase_packs;
create policy "purchase_packs_read_own"
  on public.purchase_packs for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "purchase_pack_stickers_read_own" on public.purchase_pack_stickers;
create policy "purchase_pack_stickers_read_own"
  on public.purchase_pack_stickers for select
  to authenticated
  using (
    auth.uid() = user_id
    and exists (
      select 1 from public.purchase_packs pp
      where pp.id = purchase_pack_stickers.pack_id
        and pp.status = 'opened'
    )
  );

drop policy if exists "purchase_events_read_own" on public.purchase_events;
create policy "purchase_events_read_own"
  on public.purchase_events for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.touch_purchase_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists purchase_orders_touch_updated_at on public.purchase_orders;
create trigger purchase_orders_touch_updated_at
before update on public.purchase_orders
for each row execute function public.touch_purchase_updated_at();

drop trigger if exists purchase_payments_touch_updated_at on public.purchase_payments;
create trigger purchase_payments_touch_updated_at
before update on public.purchase_payments
for each row execute function public.touch_purchase_updated_at();

drop trigger if exists purchase_packs_touch_updated_at on public.purchase_packs;
create trigger purchase_packs_touch_updated_at
before update on public.purchase_packs
for each row execute function public.touch_purchase_updated_at();

create or replace function public.open_purchased_pack(pack_id_param uuid)
returns jsonb as $$
declare
  pack_row public.purchase_packs%rowtype;
  sticker_row record;
  reveals jsonb := '[]'::jsonb;
  was_new boolean;
begin
  if auth.uid() is null then
    raise exception 'Unauthorized';
  end if;

  select *
  into pack_row
  from public.purchase_packs
  where id = pack_id_param
    and user_id = auth.uid()
  for update;

  if pack_row.id is null then
    raise exception 'Pacote nao encontrado.';
  end if;

  if pack_row.status = 'opened' then
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'slug', s.slug,
          'number', pps.sticker_number,
          'name', s.name,
          'author', s.author,
          'wasNew', pps.was_new_at_generation,
          'isRare', pps.is_rare,
          'repeat', pps.was_repeat_at_generation,
          'reward', null
        )
        order by pps.position
      ),
      '[]'::jsonb
    )
    into reveals
    from public.purchase_pack_stickers pps
    join public.stickers s on s.number = pps.sticker_number
    where pps.pack_id = pack_id_param;

    return reveals;
  end if;

  if pack_row.status <> 'pending' then
    raise exception 'Este pacote nao esta disponivel para abertura.';
  end if;

  if not exists (
    select 1
    from public.purchase_orders po
    where po.id = pack_row.order_id
      and po.user_id = auth.uid()
      and po.status in ('approved', 'partially_opened', 'completed')
  ) then
    raise exception 'Pagamento ainda nao aprovado para este pacote.';
  end if;

  update public.purchase_packs
  set status = 'opening'
  where id = pack_id_param;

  for sticker_row in
    select pps.id, pps.sticker_number, pps.is_rare, pps.position, s.slug, s.name, s.author
    from public.purchase_pack_stickers pps
    join public.stickers s on s.number = pps.sticker_number
    where pps.pack_id = pack_id_param
    order by pps.position
    for update of pps
  loop
    select not exists (
      select 1
      from public.user_stickers us
      where us.user_id = auth.uid()
        and us.sticker_number = sticker_row.sticker_number
        and us.copies > 0
    ) into was_new;

    insert into public.user_stickers (user_id, sticker_number, copies, is_rare, first_unlocked_at)
    values (auth.uid(), sticker_row.sticker_number, 1, sticker_row.is_rare, now())
    on conflict (user_id, sticker_number) do update
      set copies = public.user_stickers.copies + 1,
          is_rare = public.user_stickers.is_rare or excluded.is_rare;

    update public.purchase_pack_stickers
    set applied_to_inventory_at = coalesce(applied_to_inventory_at, now()),
        was_new_at_generation = coalesce(was_new_at_generation, was_new),
        was_repeat_at_generation = coalesce(was_repeat_at_generation, not was_new)
    where id = sticker_row.id;

    reveals := reveals || jsonb_build_object(
      'slug', sticker_row.slug,
      'number', sticker_row.sticker_number,
      'name', sticker_row.name,
      'author', sticker_row.author,
      'wasNew', was_new,
      'isRare', sticker_row.is_rare,
      'repeat', not was_new,
      'reward', null
    );
  end loop;

  update public.purchase_packs
  set status = 'opened',
      opened_at = now()
  where id = pack_id_param;

  if exists (
    select 1 from public.purchase_packs
    where order_id = pack_row.order_id
      and status = 'pending'
  ) then
    update public.purchase_orders
    set status = 'partially_opened'
    where id = pack_row.order_id;
  else
    update public.purchase_orders
    set status = 'completed',
        completed_at = coalesce(completed_at, now())
    where id = pack_row.order_id;
  end if;

  insert into public.purchase_events(order_id, user_id, event_type, message, metadata)
  values (
    pack_row.order_id,
    auth.uid(),
    'pack_opened',
    'Pacote aberto e figurinhas aplicadas ao inventario.',
    jsonb_build_object('pack_id', pack_id_param)
  );

  return reveals;
exception
  when others then
    update public.purchase_packs
    set status = 'pending'
    where id = pack_id_param
      and status = 'opening';
    raise;
end;
$$ language plpgsql security definer set search_path = public;

revoke all on function public.open_purchased_pack(uuid) from public, anon, authenticated;
grant execute on function public.open_purchased_pack(uuid) to authenticated;

insert into public.shop_products
  (id, name, description, product_type, pack_count, stickers_per_pack, price_cents, metadata)
values
  ('pack-1', '1x Pacote', 'Pacote com 5 figurinhas sortidas entre 194 e 319', 'pack', 1, 5, 250, '{"pool_start":194,"pool_end":319}'::jsonb),
  ('pack-combo', '10x Pacotes', 'Pacote com 50 figurinhas sortidas entre 194 e 319', 'combo', 10, 5, 2250, '{"pool_start":194,"pool_end":319}'::jsonb),
  ('single-random', '1x Figurinha unitaria sortida', '1x figurinha sortida entre 194 e 319', 'single_random', 1, 1, 100, '{"pool_start":194,"pool_end":319}'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  product_type = excluded.product_type,
  pack_count = excluded.pack_count,
  stickers_per_pack = excluded.stickers_per_pack,
  price_cents = excluded.price_cents,
  metadata = excluded.metadata,
  active = true,
  updated_at = now();

insert into public.shop_products
  (id, name, description, product_type, sticker_number, pack_count, stickers_per_pack, price_cents, metadata)
select
  'exclusive-' || s.number::text,
  s.name,
  'Figurinha exclusiva individual',
  'exclusive',
  s.number,
  1,
  1,
  450,
  jsonb_build_object('slug', s.slug, 'author', s.author, 'ilustrator', s.ilustrator)
from public.stickers s
where s.number between 320 and 360
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  sticker_number = excluded.sticker_number,
  price_cents = excluded.price_cents,
  metadata = excluded.metadata,
  active = true,
  updated_at = now();

grant select on public.shop_products to anon, authenticated;
grant select on
  public.purchase_orders,
  public.purchase_order_items,
  public.purchase_packs,
  public.purchase_pack_stickers,
  public.purchase_events
to authenticated;
